/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKAlternateRouteInfo : VKRouteInfo {
    struct PolylineCoordinate { 
        unsigned int index; 
        float offset; 
    }  _convergenceCoordinate;
    struct PolylineCoordinate { 
        unsigned int index; 
        float offset; 
    }  _divergenceCoordinate;
    unsigned char  _etaComparisonToMain;
}

@property (nonatomic, readonly) struct PolylineCoordinate { unsigned int x1; float x2; } convergenceCoordinate;
@property (nonatomic, readonly) struct PolylineCoordinate { unsigned int x1; float x2; } divergenceCoordinate;
@property (nonatomic) unsigned char etaComparisionToMain;

- (id).cxx_construct;
- (struct PolylineCoordinate { unsigned int x1; float x2; })convergenceCoordinate;
- (struct PolylineCoordinate { unsigned int x1; float x2; })divergenceCoordinate;
- (unsigned char)etaComparisionToMain;
- (id)initWithComposedRoute:(id)arg1 etaText:(id)arg2 uniqueStart:(struct PolylineCoordinate { unsigned int x1; float x2; })arg3 uniqueEnd:(struct PolylineCoordinate { unsigned int x1; float x2; })arg4 divergenceRouteCoordinate:(struct PolylineCoordinate { unsigned int x1; float x2; })arg5 convergenceRouteCoordinate:(struct PolylineCoordinate { unsigned int x1; float x2; })arg6;
- (void)setEtaComparisionToMain:(unsigned char)arg1;

@end
