/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKLabelManagerCollisionTimer : NSObject {
    bool  _isTimerStarted;
    struct LabelManager { int (**x1)(); struct weak_ptr<md::LabelManager> { struct LabelManager {} *x_2_1_1; struct __shared_weak_count {} *x_2_1_2; } x2; struct shared_ptr<md::TaskContext> { struct TaskContext {} *x_3_1_1; struct __shared_weak_count {} *x_3_1_2; } x3; id x4; unsigned long long x5; unsigned char x6; long long x7; unsigned char x8; unsigned char x9; bool x10; bool x11; bool x12; bool x13; bool x14; bool x15; bool x16; bool x17; bool x18; bool x19; bool x20; bool x21; bool x22; bool x23; bool x24; bool x25; bool x26; bool x27; bool x28; bool x29; bool x30; bool x31; bool x32; bool x33; struct atomic<bool> { bool x_34_1_1; } x34; bool x35; bool x36; bool x37; bool x38; bool x39; bool x40; bool x41; bool x42; bool x43; bool x44; bool x45; bool x46; bool x47; bool x48; struct Box<unsigned int, 2> { struct Matrix<unsigned int, 2, 1> { unsigned int x_1_2_1[2]; } x_49_1_1; struct Matrix<unsigned int, 2, 1> { unsigned int x_2_2_1[2]; } x_49_1_2; } x49; struct Box<unsigned int, 2> { struct Matrix<unsigned int, 2, 1> { unsigned int x_1_2_1[2]; } x_50_1_1; struct Matrix<unsigned int, 2, 1> { unsigned int x_2_2_1[2]; } x_50_1_2; } x50; } * _manager;
    VKTimer * _timer;
}

- (void)_timerFired:(id)arg1;
- (void)cancelTimer;
- (void)dealloc;
- (id)initWithManager:(struct LabelManager { int (**x1)(); struct weak_ptr<md::LabelManager> { struct LabelManager {} *x_2_1_1; struct __shared_weak_count {} *x_2_1_2; } x2; struct shared_ptr<md::TaskContext> { struct TaskContext {} *x_3_1_1; struct __shared_weak_count {} *x_3_1_2; } x3; id x4; unsigned long long x5; unsigned char x6; long long x7; unsigned char x8; unsigned char x9; bool x10; bool x11; bool x12; bool x13; bool x14; bool x15; bool x16; bool x17; bool x18; bool x19; bool x20; bool x21; bool x22; bool x23; bool x24; bool x25; bool x26; bool x27; bool x28; bool x29; bool x30; bool x31; bool x32; bool x33; struct atomic<bool> { bool x_34_1_1; } x34; bool x35; bool x36; bool x37; bool x38; bool x39; bool x40; bool x41; bool x42; bool x43; bool x44; bool x45; bool x46; bool x47; bool x48; struct Box<unsigned int, 2> { struct Matrix<unsigned int, 2, 1> { unsigned int x_1_2_1[2]; } x_49_1_1; struct Matrix<unsigned int, 2, 1> { unsigned int x_2_2_1[2]; } x_49_1_2; } x49; struct Box<unsigned int, 2> { struct Matrix<unsigned int, 2, 1> { unsigned int x_1_2_1[2]; } x_50_1_1; struct Matrix<unsigned int, 2, 1> { unsigned int x_2_2_1[2]; } x_50_1_2; } x50; }*)arg1;
- (void)killTimer;
- (void)startTimer;

@end
