/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ModelIO.framework/ModelIO
 */

@interface DAEInputSource : NSObject <NSCopying> {
    long long  _offset;
    NSString * _semantic;
    DAESource * _source;
}

@property (nonatomic) long long offset;
@property (nonatomic, retain) NSString *semantic;
@property (nonatomic, retain) DAESource *source;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (long long)offset;
- (id)semantic;
- (void)setOffset:(long long)arg1;
- (void)setSemantic:(id)arg1;
- (void)setSource:(id)arg1;
- (id)source;

@end
