/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ModelIO.framework/ModelIO
 */

@interface DAESubmeshPrimitives : NSObject {
    int * _indices;
    NSString * _type;
}

@property (nonatomic) int*indices;
@property (nonatomic, readonly, retain) NSString *type;

- (void).cxx_destruct;
- (void)dealloc;
- (int*)indices;
- (void)setIndices:(int*)arg1;
- (id)type;

@end
