/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ModelIO.framework/ModelIO
 */

@interface DAEVertexSource : NSObject {
    NSArray * _inputs;
}

@property (nonatomic, retain) NSArray *inputs;

- (void).cxx_destruct;
- (id)inputs;
- (void)setInputs:(id)arg1;

@end
