/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ModelIO.framework/ModelIO
 */

@interface MDLAnimatedValue : NSObject <MDLNamed, NSCopying> {
    unsigned long long  _interpolation;
    NSString * _name;
    struct vector<(anonymous namespace)::TimeSampledVtValue, std::__1::allocator<(anonymous namespace)::TimeSampledVtValue> >="__begin_"^{TimeSampledVtValue {}  _timeSampledData;
}

@property (nonatomic) unsigned long long interpolation;
@property (nonatomic, readonly) NSArray *keyTimes;
@property (nonatomic, readonly) double maximumTime;
@property (nonatomic, readonly) double minimumTime;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, readonly) unsigned long long precision;
@property (nonatomic, readonly) unsigned long long timeSampleCount;

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)clear;
- (unsigned long long)copyTimesInto:(double*)arg1 maxCount:(unsigned long long)arg2;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (struct VtValue { struct aligned_storage_imp<8, 8> { union data_t { BOOL x_1_2_1[8]; struct a8 { } x_1_2_2; } x_1_1_1; } x1; struct TfPointerAndBits<const VtValue::_TypeInfo> { struct _TypeInfo {} *x_2_1_1; } x2; })defaultVtValue;
- (id)initWithName:(id)arg1;
- (unsigned long long)interpolation;
- (bool)isAnimated;
- (id)keyTimes;
- (double)maximumTime;
- (double)minimumTime;
- (id)name;
- (unsigned long long)precision;
- (void)resetWithUsdAttribute:(const struct UsdAttribute { int x1; struct Usd_PrimDataHandle { struct intrusive_ptr<const Usd_PrimData> { struct Usd_PrimData {} *x_1_2_1; } x_2_1_1; } x2; struct TfToken { struct TfPointerAndBits<const TfToken::_Rep> { struct _Rep {} *x_1_2_1; } x_3_1_1; } x3; }*)arg1 timeScale:(double)arg2;
- (void)setInterpolation:(unsigned long long)arg1;
- (void)setName:(id)arg1;
- (unsigned long long)timeSampleCount;

@end
