/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
 */

@interface _LSConcreteLazyPropertyList : _LSLazyPropertyList {
    NSData * _plistData;
    id  _plistHint;
}

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (bool)_getValue:(id*)arg1 forPropertyListKey:(id)arg2;
- (id)_loadPropertyListPeeking:(bool)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithPropertyListData:(id)arg1;

@end
