/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/FileProvider.framework/FileProvider
 */

@interface _FPCopyOrMoveOperation : FPActionOperation <NSProgressReporting> {
    FPItem * _destinationFolder;
    NSString * _destinationName;
    bool  _isCopyOperation;
    unsigned long long  _lastUsedDatePolicy;
    id /* block */  _operationCompletionBlock;
    NSOperationQueue * _operationQueue;
    NSProgress * _progress;
    bool  _recursiveOperation;
    bool  _shouldBounceOnCollision;
    long long  _sourceFileSize;
    FPItem * _sourceItem;
    NSURL * _sourceURL;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) id /* block */ operationCompletionBlock;
@property (readonly) NSProgress *progress;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_incrementProgressBy:(unsigned long long)arg1;
- (void)downloadItemIfNecessaryWithCompletionHandler:(id /* block */)arg1;
- (void)enumerateAndCopyChildren;
- (void)finishWithResult:(id)arg1 error:(id)arg2;
- (id)initWithItem:(id)arg1 destinationFolder:(id)arg2 copyItem:(bool)arg3 lastUsageUpdatePolicy:(unsigned long long)arg4 bounceOnCollision:(bool)arg5 operationQueue:(id)arg6;
- (id)initWithURL:(id)arg1 destinationFolder:(id)arg2 name:(id)arg3 copyItem:(bool)arg4 lastUsageUpdatePolicy:(unsigned long long)arg5 bounceOnCollision:(bool)arg6 operationQueue:(id)arg7;
- (void)mainWithExtensionProxy:(id)arg1;
- (id /* block */)operationCompletionBlock;
- (id)progress;
- (void)resolveItemOrURLWithCompletionHandler:(id /* block */)arg1;
- (void)setOperationCompletionBlock:(id /* block */)arg1;

@end
