/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/FileProvider.framework/FileProvider
 */

@interface FPDownloadOperation : FPActionOperation {
    NSFileCoordinator * _fileCoordinator;
    NSArray * _items;
}

- (void).cxx_destruct;
- (oneway void)cancel;
- (id)initWithItems:(id)arg1;
- (void)main;
- (void)presendNotifications;

@end
