/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/FileProvider.framework/FileProvider
 */

@interface FPOperation : NSOperation <FPOperationClient> {
    id  _executionTransaction;
    bool  _finished;
    NSObject<OS_dispatch_queue> * _queue;
    <FPCancellable> * _remoteOperation;
    unsigned char  _uuid;
}

@property (nonatomic, retain) NSObject<OS_dispatch_queue> *callbackQueue;
@property (getter=isExecuting, readonly) bool executing;
@property (getter=isFinished, readonly) bool finished;
@property (nonatomic, retain) <FPCancellable> *remoteOperation;

- (void).cxx_destruct;
- (bool)_finishIfCancelled;
- (void)_setExecuting:(bool)arg1;
- (void)_setFinished:(bool)arg1;
- (void)_setRemoteCancellationHandler:(id)arg1;
- (id)callbackQueue;
- (oneway void)cancel;
- (void)completedWithResult:(id)arg1 error:(id)arg2;
- (void)dealloc;
- (id)description;
- (bool)finishIfCancelled;
- (void)finishWithResult:(id)arg1 error:(id)arg2;
- (id)init;
- (oneway void)invalidate;
- (bool)isExecuting;
- (bool)isFinished;
- (void)operationDidProgressWithIdentifier:(id)arg1 data:(id)arg2 error:(id)arg3 completionHandler:(id /* block */)arg4;
- (id)remoteOperation;
- (void)setCallbackQueue:(id)arg1;
- (oneway void)setCancellationHandler:(id)arg1;
- (void)setRemoteOperation:(id)arg1;
- (void)start;

@end
