/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/FileProvider.framework/FileProvider
 */

@interface FPTrashOperation : FPActionOperation {
    NSArray * _items;
}

- (void).cxx_destruct;
- (id)initWithItems:(id)arg1;
- (void)mainWithExtensionProxy:(id)arg1;
- (void)presendNotifications;
- (id)replicateForItems:(id)arg1;

@end
