/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/FileProvider.framework/FileProvider
 */

@interface FPXIndexItemsOperation : FPOperation {
    id /* block */  _indexCompletedBlock;
    FPXSpotlightIndexer * _indexer;
    unsigned long long * _logSection;
    NSArray * _updatedItems;
}

@property (nonatomic, copy) id /* block */ indexCompletedBlock;
@property (nonatomic, retain) NSArray *updatedItems;

- (void).cxx_destruct;
- (void)finishWithResult:(id)arg1 error:(id)arg2;
- (id /* block */)indexCompletedBlock;
- (id)initWithIndexer:(id)arg1;
- (void)main;
- (void)setIndexCompletedBlock:(id /* block */)arg1;
- (void)setUpdatedItems:(id)arg1;
- (id)updatedItems;

@end
