/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/FileProvider.framework/FileProvider
 */

@interface FPXXPCListenerMessagingConfiguration : FPXXPCListenerConfiguration {
    NSFileProviderMessageInterface * _messageInterface;
}

- (void).cxx_destruct;
- (id)initWithMessageInterface:(id)arg1 context:(id)arg2;
- (bool)setupDelegate:(id)arg1 error:(id*)arg2;

@end
