/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContactsDonation.framework/ContactsDonation
 */

@interface CNDCoreTelephonyServices : NSObject <CNDCoreTelephonyServices>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void)addObserver:(struct __CTServerConnection { }*)arg1 :(const void*)arg2 :(int (*)arg3 :(struct __CFString { }*)arg4 :(const void*)arg5 :(long long)arg6;
- (id)copyMyPhoneNumber;
- (struct __CTServerConnection { }*)defaultCenter;
- (void)removeObserver:(struct __CTServerConnection { }*)arg1 :(const void*)arg2 :(struct __CFString { }*)arg3 :(const void*)arg4;

@end
