/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContactsDonation.framework/ContactsDonation
 */

@interface CNDPhoneNumberMonitor : NSObject <CNDPhoneNumberMonitor> {
    <CNDCoreTelephonyServices> * _coreTelephonyServices;
    CNReplaySubject * _subject;
    <CNCancelable> * _subjectToken;
}

@property (nonatomic, readonly) <CNDCoreTelephonyServices> *coreTelephonyServices;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) CNReplaySubject *subject;
@property (nonatomic, retain) <CNCancelable> *subjectToken;
@property (readonly) Class superclass;

+ (id)continuousPhoneNumberObservableWithCoreTelephonyServices:(id)arg1;
+ (id)phoneNumberChangedObservableWithCoreTelephonyServices:(id)arg1;
+ (id)phoneNumberObservableWithCoreTelephonyServices:(id)arg1;

- (void).cxx_destruct;
- (id)addPhoneNumberChangeHandler:(id /* block */)arg1;
- (void)configureSubjectIfNecessary;
- (id)coreTelephonyServices;
- (void)dealloc;
- (id)init;
- (id)initWithTelephonyServices:(id)arg1;
- (void)setSubjectToken:(id)arg1;
- (id)subject;
- (id)subjectToken;

@end
