/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSXPCConnectionRequestedReplies : NSObject {
    struct _opaque_pthread_mutex_t { 
        long long __sig; 
        BOOL __opaque[56]; 
    }  _lock;
    struct __CFDictionary { } * _replyTable;
}

- (void)addSequence:(unsigned long long)arg1 withProgress:(id)arg2 cleanupBlock:(id /* block */)arg3;
- (void)cleanup;
- (void)dealloc;
- (id)init;
- (id)progressForSequence:(unsigned long long)arg1;
- (bool)removeSequence:(unsigned long long)arg1;

@end
