/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSXPCInterfaceInfo : NSObject {
    struct __CFDictionary { } * _knownSelectors;
    struct _opaque_pthread_rwlock_t { 
        long long __sig; 
        BOOL __opaque[192]; 
    }  _knownSelectorsLock;
    struct __CFDictionary { } * _methodInfo;
    unsigned long long  _remoteVersion;
    Class  _xpcDOSubclass;
}

@property unsigned long long remoteVersion;

- (void)dealloc;
- (id)init;
- (unsigned long long)remoteVersion;
- (void)setRemoteVersion:(unsigned long long)arg1;

@end
