/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
 */

@interface CLServiceVendor : NSObject {
    NSMutableDictionary * _catalog;
    int  _missBehavior;
    NSDictionary * _serviceReplacementMap;
}

+ (void)initialize;
+ (void)rereadConfiguration;
+ (id)sharedInstance;

- (void).cxx_destruct;
- (bool)ensureServiceIsRunning:(id)arg1;
- (id)getServiceWithName:(id)arg1;
- (id)getSiloForService:(id)arg1;
- (id)init;
- (bool)isServiceEnabled:(id)arg1;
- (bool)isServiceRunning:(id)arg1;
- (id)proxyForService:(id)arg1;
- (id)proxyForService:(id)arg1 forClient:(id)arg2;
- (void)retireServiceWithName:(id)arg1;
- (void)setServiceReplacementMap:(id)arg1 missBehavior:(int)arg2;

@end
