/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
 */

@interface CMFunctionalCapacityData : NSObject <NSCopying, NSSecureCoding> {
    double  fEstimatedVo2Max;
    unsigned long long  fRecordId;
    NSUUID * fSourceId;
    NSDate * fTimestamp;
}

@property (nonatomic, readonly) double estimatedVo2Max;
@property (nonatomic, readonly) unsigned long long recordId;
@property (nonatomic, readonly) NSUUID *sourceId;
@property (nonatomic, readonly) NSDate *timestamp;

+ (bool)supportsSecureCoding;

- (void)convertToFunctionalCapacityEntry:(struct CLFunctionalCapacityEntry { unsigned long long x1; unsigned char x2[16]; double x3; double x4; int x5; double x6; double x7; double x8; double x9; }*)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (double)estimatedVo2Max;
- (id)initWithCoder:(id)arg1;
- (id)initWithFunctionalCapacityEntry:(const struct CLFunctionalCapacityEntry { unsigned long long x1; unsigned char x2[16]; double x3; double x4; int x5; double x6; double x7; double x8; double x9; }*)arg1;
- (id)initWithRecordId:(unsigned long long)arg1 sourceId:(id)arg2 timestamp:(id)arg3 estimatedVo2Max:(double)arg4;
- (unsigned long long)recordId;
- (id)sourceId;
- (id)timestamp;

@end
