/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
 */

@interface CMFunctionalCapacity : NSObject {
    CMFunctionalCapacityInternal * _internal;
}

@property (nonatomic, readonly) CMFunctionalCapacityInternal *_internal;

+ (bool)isAvailable;

- (id)_internal;
- (void)dealloc;
- (id)init;
- (void)startUpdatesFromRecord:(id)arg1 handler:(id /* block */)arg2;
- (void)stopUpdates;

@end
