/* Generated by RuntimeBrowser.
 */

@protocol _UIButtonBarAppearanceDelegate

@required

- (double)absorptionForItem:(UIBarButtonItem *)arg1;
- (id)appearanceStorage;
- (double)backButtonMargin;
- (UIImage *)backIndicatorImage;
- (UIImage *)backIndicatorMaskImage;
- (long long)barMetrics;
- (long long)barType;
- (bool)barWantsLetterpress;
- (bool)centerTextButtons;
- (double)defaultEdgeSpacing;
- (UIFontDescriptor *)defaultFontDescriptor;
- (unsigned long long)edgesPaddingBarButtonItem:(UIBarButtonItem *)arg1;
- (UIColor *)tintColor;

@end
