/* Generated by RuntimeBrowser.
 */

@protocol _UITableViewDragControllerDelegate <NSObject>

@required

- (void)_beginAnimatingDropOfCell:(UITableViewCell *)arg1;
- (bool)_canBeginDragAtPoint:(struct CGPoint { double x1; double x2; })arg1 indexPath:(NSIndexPath *)arg2;
- (UIDragPreviewParameters *)_dragPreviewParametersForIndexPath:(NSIndexPath *)arg1;
- (void)_dragSessionDidEnd:(id <UIDragSession>)arg1;
- (void)_dragSessionWillBegin:(id <UIDragSession>)arg1;
- (void)_endAnimatingDropOfCell:(UITableViewCell *)arg1;
- (NSArray *)_itemsForAddingToDragSession:(id <UIDragSession>)arg1 atIndexPath:(NSIndexPath *)arg2 point:(struct CGPoint { double x1; double x2; })arg3;
- (NSArray *)_itemsForBeginningDragSession:(id <UIDragSession>)arg1 atIndexPath:(NSIndexPath *)arg2;
- (void)_prepareForDragLiftOfRowsAtIndexPaths:(NSOrderedSet *)arg1;
- (NSOrderedSet *)_rowsToIncludeInDragAtIndexPath:(NSIndexPath *)arg1;
- (void)_updateAppearanceForRowsInDrag;

@end
