/* Generated by RuntimeBrowser.
 */

@protocol _UITableViewDropCoordinatorDelegate <_UITableViewPlaceholderContextDelegate>

@required

- (void)animateDragItem:(UIDragItem *)arg1 intoRowAtIndexPath:(NSIndexPath *)arg2 rect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg3;
- (void)animateDragItem:(UIDragItem *)arg1 toCell:(UITableViewCell *)arg2 withPreviewParameters:(UIDragPreviewParameters *)arg3;
- (void)animateDragItem:(UIDragItem *)arg1 toRowAtIndexPath:(NSIndexPath *)arg2 withPreviewParameters:(UIDragPreviewParameters *)arg3;
- (void)animateDragItem:(UIDragItem *)arg1 toTarget:(UIDragPreviewTarget *)arg2;
- (void)insertPlaceholderAtIndexPath:(NSIndexPath *)arg1 withContext:(_UITableViewDropPlaceholderContextImpl *)arg2;
- (UITableView *)tableView;

@end
