/* Generated by RuntimeBrowser.
 */

@protocol AVOutputContextImpl <NSObject, NSSecureCoding>

@required

+ (id)auxiliaryOutputContext;
+ (id)iTunesAudioContext;
+ (bool)outputContextExistsWithRemoteOutputDevice;
+ (id)outputContextForControllingOutputDeviceGroup:(AVOutputDeviceGroup *)arg1;
+ (id)outputContextForControllingOutputDeviceGroupWithID:(NSString *)arg1;
+ (id)platformDependentScreenOrVideoContext;
+ (void)resetOutputDeviceForAllOutputContexts;
+ (id)sharedAudioPresentationOutputContext;
+ (id)sharedSystemAudioContext;
+ (id)sharedSystemScreenContext;

- (NSString *)ID;
- (void)addOutputDevice:(AVOutputDevice *)arg1;
- (NSString *)associatedAudioDeviceID;
- (AVOutputContextCommunicationChannel *)outgoingCommunicationChannel;
- (void)outputContextDidChangeApplicationProcessID:(AVOutputContext *)arg1;
- (AVOutputDevice *)outputDevice;
- (AVOutputDeviceGroup *)outputDeviceGroup;
- (NSArray *)outputDevices;
- (AVOutputContext *)parentOutputContext;
- (void)removeOutputDevice:(AVOutputDevice *)arg1;
- (bool)setOutputDevice:(AVOutputDevice *)arg1 options:(NSDictionary *)arg2;
- (void)setOutputDevices:(NSArray *)arg1;
- (void)setParentOutputContext:(AVOutputContext *)arg1;

@end
