/* Generated by RuntimeBrowser.
 */

@protocol AVPlayerViewControllerContentViewDelegate <NSObject>

@required

- (struct CGSize { double x1; double x2; })playerViewControllerContentViewContentDimensions;
- (NSString *)playerViewControllerContentViewVideoGravity;
- (void)playerViewControllerContentViewWillLayoutSubviews:(AVPlayerViewControllerContentView *)arg1;

@end
