/* Generated by RuntimeBrowser.
 */

@protocol AVRoutePickerHostViewControllerDelegate <NSObject>

@required

- (void)routePickerHostViewControllerWantsDismissal:(AVRoutePickerHostViewController *)arg1;

@end
