/* Generated by RuntimeBrowser.
 */

@protocol CNDCoreTelephonyServices <NSObject>

@required

- (void)addObserver:(struct __CTServerConnection { }*)arg1 :(const void*)arg2 :(int (*)arg3 :(const struct __CFString { }*)arg4 :(const void*)arg5 :(long long)arg6;
- (NSString *)copyMyPhoneNumber;
- (struct __CTServerConnection { }*)defaultCenter;
- (void)removeObserver:(struct __CTServerConnection { }*)arg1 :(const void*)arg2 :(const struct __CFString { }*)arg3 :(const void*)arg4;

@end
