/* Generated by RuntimeBrowser.
 */

@protocol CNDonationLoggerProvider <NSObject>

@required

- (<CNDonationAccountLogger> *)accountLogger;
- (<CNDonationAgentLogger> *)agentLogger;
- (<CNDonationExtensionLogger> *)extensionLogger;
- (<CNDonationPreferencesLogger> *)preferencesLogger;
- (<CNDonationToolLogger> *)toolLogger;

@end
