/* Generated by RuntimeBrowser.
 */

@protocol CNDonationAgentLogger <NSObject>

@required

- (void)acceptingConnectionFromProcess:(int)arg1;
- (void)acceptingDonations:(NSArray *)arg1;
- (void)agentDidHandleRequest:(SEL)arg1;
- (void)agentDidStart;
- (void)agentWillHandleRequest:(SEL)arg1;
- (void)agentWillStart;
- (void)agentWillStop;
- (void)beginRestorePersistedState;
- (void)couldNotRejectUnknownCollectionIdentifier:(NSString *)arg1;
- (void)couldNotRejectUnknownDonationIdentifier:(NSString *)arg1;
- (void)denyingRequestFromProcess:(int)arg1;
- (void)didDiscoverExtension:(CNDDonorExtension *)arg1;
- (void)didDiscoverExtensions;
- (void)didDiscoverUnexpectedExtensionType:(id)arg1;
- (void)didFailToDiscoverExtensions:(NSError *)arg1;
- (void)didListRejections;
- (void)didRejectCollectionIdentifier:(NSString *)arg1;
- (void)didRejectDonationIdentifier:(NSString *)arg1;
- (void)didRemoveAllRejections;
- (void)donationServiceDidStart;
- (void)donationServiceWillStart;
- (void)donationServiceWillStop;
- (void)endRestorePersistedState;
- (void)featureDidDisable;
- (void)featureDidEnable;
- (void)featureNotEnabled:(SEL)arg1;
- (void)featureWillDisable;
- (void)featureWillEnable;
- (void)maintenanceServiceDidStart;
- (void)maintenanceServiceWillStart;
- (void)maintenanceServiceWillStop;
- (void)preExpiredDonations:(NSArray *)arg1;
- (void)willDiscoverExtensions;
- (void)willListRejections;
- (void)willLoadExtensionVersions;
- (void)willRejectCollectionIdentifier:(NSString *)arg1;
- (void)willRejectDonationIdentifier:(NSString *)arg1;
- (void)willRemoveAllRejections;
- (void)willSaveExtensionVersions;

@end
