/* Generated by RuntimeBrowser.
 */

@protocol DOCNavigationBarOverwriteProtocol <NSObject>

@optional

- (bool)isTopNavigationItem;
- (UIBarButtonItem *)overriddenLeftButton;
- (NSString *)overriddenTitle;
- (void)setIsTopNavigationItem:(bool)arg1;
- (void)setOverriddenLeftButton:(UIBarButtonItem *)arg1;
- (void)setOverriddenTitle:(NSString *)arg1;

@end
