/* Generated by RuntimeBrowser.
 */

@protocol DOCSourceViewControllerDelegate <NSObject>

@optional

- (void)sourceViewController:(DOCSourceViewController *)arg1 didSelectLocation:(DOCConcreteLocation *)arg2;

@end
