/* Generated by RuntimeBrowser.
 */

@protocol FPUIActionViewControllerDelegate <NSObject>

@required

- (void)actionControllerDidFinishAction:(FPUIActionViewController *)arg1 error:(NSError *)arg2;

@end
