/* Generated by RuntimeBrowser.
 */

@protocol GEOVenueIdentifier <NSObject>

@required

- (bool)_hasMUID;
- (bool)_hasVenueID;
- (NSArray *)componentIdentifiers;
- (unsigned long long)muid;
- (GEOPDVenueIdentifier *)placeDataVenueIdentifierForBuilding:(id <GEOVenueComponentIdentifier>)arg1;
- (GEOPDVenueIdentifier *)placeDataVenueIdentifierForVenue;
- (unsigned long long)venueID;

@end
