/* Generated by RuntimeBrowser.
 */

@protocol INCreateTaskListIntentExport <NSObject, JSExport>

@required

- (INSpeakableString *)groupName;
- (id)init;
- (void)setGroupName:(INSpeakableString *)arg1;
- (void)setTaskTitles:(NSArray *)arg1;
- (void)setTitle:(NSString *)arg1;
- (NSArray *)taskTitles;
- (NSString *)title;

@end
