/* Generated by RuntimeBrowser.
 */

@protocol INCreateNoteIntentExport <NSObject, JSExport>

@required

- (INNoteContent *)content;
- (INSpeakableString *)groupName;
- (id)init;
- (void)setContent:(INNoteContent *)arg1;
- (void)setGroupName:(INSpeakableString *)arg1;
- (void)setTitle:(NSString *)arg1;
- (NSString *)title;

@end
