/* Generated by RuntimeBrowser.
 */

@protocol MRTelevisionDelegate <NSObject>

@optional

- (void)televisionController:(MRTelevisionController *)arg1 didDiscoverTelevision:(MRTelevisionDevice *)arg2;
- (void)televisionController:(MRTelevisionController *)arg1 didRemoveTelevision:(MRTelevisionDevice *)arg2;

@end
