/* Generated by RuntimeBrowser.
 */

@protocol MTLFunctionSPI <MTLFunction>

@required

- (NSArray *)arguments;
- (NSString *)filePath;
- (long long)lineNumber;
- (MTLFunctionReflection *)reflectionWithOptions:(unsigned long long)arg1;
- (void)reflectionWithOptions:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 7: unsigned long long, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, MTLFunctionReflection *, void*
- (MTLType *)returnType;

@end
