/* Generated by RuntimeBrowser.
 */

@protocol NSItemProviderReading <NSObject>

@required

+ (NSArray *)readableTypeIdentifiersForItemProvider;

- (id)initWithItemProviderData:(NSData *)arg1 typeIdentifier:(NSString *)arg2 error:(id*)arg3;

@end
