/* Generated by RuntimeBrowser.
 */

@protocol PBDataTransferMonitorDelegate <NSObject>

@required

- (void)dataTransferMonitorBeganTransfers:(PBDataTransferMonitor *)arg1;
- (void)dataTransferMonitorFinishedTransfers:(PBDataTransferMonitor *)arg1;

@end
