/* Generated by RuntimeBrowser.
 */

@protocol UIDictationConnectionTokenFilterProtocol <NSObject>

@required

- (void)dictationConnection:(UIDictationConnection *)arg1 didFilterTokensWithFilterState:(id)arg2 forFinalize:(bool)arg3;
- (void)dictationConnection:(UIDictationConnection *)arg1 filterState:(id)arg2 processFilteredToken:(UIDictationToken *)arg3 forFinalize:(bool)arg4;
- (UIDictationToken *)dictationConnection:(UIDictationConnection *)arg1 filterState:(id)arg2 token:(UIDictationToken *)arg3 secureInput:(bool)arg4 forFinalize:(bool)arg5;
- (id)dictationConnection:(UIDictationConnection *)arg1 willFilterTokensWithLanguageModel:(NSString *)arg2 forFinalize:(bool)arg3;

@end
