/* Generated by RuntimeBrowser.
 */

@protocol UIDragInteractionDelegate_Private <UIDragInteractionDelegate>

@optional

- (bool)_dragInteraction:(UIDragInteraction *)arg1 canExcludeCompetingGestureRecognizer:(UIGestureRecognizer *)arg2;
- (bool)_dragInteraction:(UIDragInteraction *)arg1 competingGestureRecognizerShouldDelayLift:(UIGestureRecognizer *)arg2;
- (bool)_dragInteraction:(UIDragInteraction *)arg1 shouldCancelOnAppDeactivationWithDefault:(bool)arg2;
- (bool)_dragInteraction:(UIDragInteraction *)arg1 shouldDelayCompetingGestureRecognizer:(UIGestureRecognizer *)arg2;
- (bool)_dragInteractionAllowsDragOverridingMasterSwitch:(UIDragInteraction *)arg1;

@end
