/* Generated by RuntimeBrowser.
 */

@protocol UITextDropSupporting <UITextDroppable, UITextPasteConfigurationSupporting>

@required

- (bool)allowsEditingTextAttributes;
- (void)becomeDropResponder;
- (UIView *)dropTargetContainerView;
- (void)resignDropResponder;

@optional

- (struct CGPoint { double x1; double x2; })contentOffsetForSameViewDrops;
- (void)setContentOffsetForSameViewDrops:(struct CGPoint { double x1; double x2; })arg1;

@end
