/* Generated by RuntimeBrowser.
 */

@protocol UITextPasteSessionDelegate <NSObject>

@optional

- (void)textPasteSessionDidFinishPasting:(id <UITextPasteSession>)arg1;
- (void)textPasteSessionWillBlockPasting:(id <UITextPasteSession>)arg1;

@end
