/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

@interface TIAutopunctuationController : NSObject {
    bool  _leftDoubleQuotationMarkInserted;
}

- (void)reset;
- (id)stringForInputString:(id)arg1 inputMangerState:(id)arg2 isVariant:(bool)arg3;

@end
