/* Generated by RuntimeBrowser
   Image: /usr/lib/libAWDSupportFramework.dylib
 */

@interface AWDIDSGenericConnectionSetupDurationEvent : PBCodable <NSCopying> {
    unsigned long long  _connectionSetupDuration;
    struct { 
        unsigned int connectionSetupDuration : 1; 
        unsigned int timestamp : 1; 
        unsigned int linkType : 1; 
    }  _has;
    unsigned int  _linkType;
    unsigned long long  _timestamp;
}

@property (nonatomic) unsigned long long connectionSetupDuration;
@property (nonatomic) bool hasConnectionSetupDuration;
@property (nonatomic) bool hasLinkType;
@property (nonatomic) bool hasTimestamp;
@property (nonatomic) unsigned int linkType;
@property (nonatomic) unsigned long long timestamp;

- (unsigned long long)connectionSetupDuration;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasConnectionSetupDuration;
- (bool)hasLinkType;
- (bool)hasTimestamp;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (unsigned int)linkType;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setConnectionSetupDuration:(unsigned long long)arg1;
- (void)setHasConnectionSetupDuration:(bool)arg1;
- (void)setHasLinkType:(bool)arg1;
- (void)setHasTimestamp:(bool)arg1;
- (void)setLinkType:(unsigned int)arg1;
- (void)setTimestamp:(unsigned long long)arg1;
- (unsigned long long)timestamp;
- (void)writeTo:(id)arg1;

@end
