/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVKit.framework/AVKit
 */

@interface AVFullScreenTransition : AVTransition {
    AVFullScreenViewController * _fullScreenViewController;
    bool  _prefersBlackBarsDuringTransition;
}

@property (nonatomic, readonly) AVFullScreenViewController *fullScreenViewController;
@property (nonatomic) bool prefersBlackBarsDuringTransition;

- (void).cxx_destruct;
- (id)backgroundView;
- (void)completeTransition:(bool)arg1;
- (id)fullScreenViewController;
- (bool)prefersBlackBarsDuringTransition;
- (void)setPrefersBlackBarsDuringTransition:(bool)arg1;
- (bool)shouldRemovePresentingView;
- (void)transitionWillBegin;

@end
