/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVKit.framework/AVKit
 */

@interface AVPlayerViewControllerContentView : UIView {
    AVAudioOnlyIndicatorView * _audioOnlyIndicatorView;
    UIView * _contentOverlayView;
    <AVPlayerViewControllerContentViewDelegate> * _delegate;
    AVExternalPlaybackIndicatorView * _externalPlaybackIndicatorView;
    UIView * _iAdPreRollView;
    bool  _needsInitialLayout;
    AVPlaybackControlsView * _playbackControlsView;
    UIView * _playerLayerAndContentOverlayContainerView;
    UIView * _playerLayerView;
    AVStatusBarBackgroundGradientView * _statusBarBackgroundGradientView;
    AVUnsupportedContentIndicatorView * _unsupportedContentIndicatorView;
}

@property (nonatomic, readonly) AVAudioOnlyIndicatorView *audioOnlyIndicatorView;
@property (nonatomic, readonly) UIView *contentOverlayView;
@property (nonatomic) <AVPlayerViewControllerContentViewDelegate> *delegate;
@property (nonatomic, readonly) AVExternalPlaybackIndicatorView *externalPlaybackIndicatorView;
@property (nonatomic, readonly) UIView *iAdPreRollView;
@property (nonatomic, readonly) UIView *interactiveContentOverlayView;
@property (nonatomic, readonly) bool isCoveringWindow;
@property (nonatomic, readonly) bool isDescendantOfNonPagingScrollView;
@property (nonatomic) bool needsInitialLayout;
@property (nonatomic, readonly) AVPlaybackControlsView *playbackControlsView;
@property (nonatomic, readonly) UIView *playerLayerAndContentOverlayContainerView;
@property (nonatomic, readonly) UIView *playerLayerView;
@property (nonatomic, readonly) AVStatusBarBackgroundGradientView *statusBarBackgroundGradientView;
@property (nonatomic, readonly) AVUnsupportedContentIndicatorView *unsupportedContentIndicatorView;

- (void).cxx_destruct;
- (void)addPlayerLayerAndContentOverlayContainerViewIfNeeded;
- (id)audioOnlyIndicatorView;
- (id)contentOverlayView;
- (void)dealloc;
- (id)delegate;
- (id)externalPlaybackIndicatorView;
- (id)iAdPreRollView;
- (id)initWithPlayerLayerView:(id)arg1;
- (id)interactiveContentOverlayView;
- (bool)isCoveringWindow;
- (bool)isDescendantOfNonPagingScrollView;
- (bool)isViewDescendantOfPlaybackControlsSubview:(id)arg1;
- (void)layoutSubviews;
- (bool)needsInitialLayout;
- (id)playbackControlsView;
- (id)playerLayerAndContentOverlayContainerView;
- (id)playerLayerView;
- (void)setDelegate:(id)arg1;
- (void)setExternalPlaybackIndicatorTitle:(id)arg1 subtitle:(id)arg2;
- (void)setNeedsInitialLayout:(bool)arg1;
- (void)setShowsAudioOnlyIndicator:(bool)arg1;
- (void)setShowsExternalPlaybackIndicator:(bool)arg1;
- (void)setShowsUnsupportedContentIndicator:(bool)arg1;
- (id)statusBarBackgroundGradientView;
- (id)unsupportedContentIndicatorView;
- (void)updatePlayerLayerAndContentOverlayContainerViewLayoutMarginsForVideoGravity:(id)arg1;

@end
