/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVKit.framework/AVKit
 */

@interface AVTransition : NSObject {
    UIView * _backgroundView;
    UIViewPropertyAnimator * _currentAnimator;
    AVPlayerViewController * _playerViewController;
    <UIViewControllerContextTransitioning> * _transitionContext;
    bool  _wasInitiallyInteractive;
}

@property (nonatomic, readonly) UIView *backgroundView;
@property (nonatomic, readonly) UIView *containerView;
@property (nonatomic) UIViewPropertyAnimator *currentAnimator;
@property (nonatomic, readonly) double duration;
@property (nonatomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } finalFrameForFromViewController;
@property (nonatomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } finalFrameForToViewController;
@property (nonatomic, readonly) UIView *fromView;
@property (nonatomic, readonly) UIViewController *fromViewController;
@property (nonatomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } initialFrameForFromViewController;
@property (nonatomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } initialFrameForToViewController;
@property (getter=isInteractive, nonatomic, readonly) bool interactive;
@property (nonatomic, readonly) AVPlayerViewController *playerViewController;
@property (nonatomic, readonly) UIView *toView;
@property (nonatomic, readonly) UIViewController *toViewController;
@property (nonatomic, readonly) <UIViewControllerContextTransitioning> *transitionContext;
@property (nonatomic) bool wasInitiallyInteractive;

+ (struct CGAffineTransform { double x1; double x2; double x3; double x4; double x5; double x6; })transformForPercentComplete:(double)arg1 fromScale:(double)arg2 toScale:(double)arg3 rotation:(double)arg4 translation:(struct CGPoint { double x1; double x2; })arg5;
+ (id)transitionWithTransitionContext:(id)arg1 playerViewController:(id)arg2;

- (void).cxx_destruct;
- (void)animateAlongsideInteractiveTransitionAnimationForCancelling;
- (void)animateAlongsideInteractiveTransitionAnimationForFinishing;
- (void)animateAlongsideNonInteractiveTransitionAnimation;
- (void)animateNonInteractiveTransition;
- (id)backgroundView;
- (void)cancelInteractiveTransition;
- (void)completeTransition:(bool)arg1;
- (id)containerView;
- (id)currentAnimator;
- (void)dealloc;
- (double)duration;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })finalFrameForFromViewController;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })finalFrameForToViewController;
- (void)finishInteractiveTransition;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frameForPlayerViewControllerInContainerView;
- (id)fromView;
- (id)fromViewController;
- (id)initWithTransitionContext:(id)arg1 playerViewController:(id)arg2;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })initialFrameForFromViewController;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })initialFrameForToViewController;
- (bool)isInteractive;
- (void)pauseInteractiveTransition;
- (id)playerViewController;
- (void)setCurrentAnimator:(id)arg1;
- (void)setWasInitiallyInteractive:(bool)arg1;
- (id)toView;
- (id)toViewController;
- (id)transitionContext;
- (void)transitionWillBegin;
- (void)updateWithPercentComplete:(double)arg1 translation:(struct CGPoint { double x1; double x2; })arg2 rotation:(double)arg3;
- (bool)wasInitiallyInteractive;

@end
