/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPMediaControlsRemoteViewController : _UIRemoteViewController

+ (id)exportedInterface;
+ (id)serviceViewControllerInterface;

@end
