/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPNowPlayingInfoCenter : NSObject {
    void * _artworkToken;
    bool  _coalescingUpdates;
    NSMutableSet * _contentItemIdentifiersSentToMediaRemote;
    NSDictionary * _convertedNowPlayingInfo;
    void * _createChildItemToken;
    void * _createItemForIdentifierToken;
    void * _createItemForOffsetToken;
    void * _createPlaybackQueueToken;
    void * _infoToken;
    void * _languageOptionsToken;
    <MPNowPlayingInfoLyricsDelegate> * _lyricsDelegate;
    void * _lyricsToken;
    void * _metadataToken;
    NSMutableDictionary * _mutatedContentItems;
    NSDictionary * _nowPlayingInfo;
    <MPNowPlayingPlaybackQueueDataSource> * _playbackQueueDataSource;
    <MPNowPlayingPlaybackQueueDelegate> * _playbackQueueDelegate;
    unsigned long long  _playbackState;
    NSString * _playerID;
    void * _playerPath;
    NSDate * _pushDate;
    NSObject<OS_dispatch_queue> * _queue;
    NSDictionary * _queuedNowPlayingInfo;
}

@property (nonatomic) <MPNowPlayingInfoLyricsDelegate> *lyricsDelegate;
@property (copy) NSDictionary *nowPlayingInfo;
@property (nonatomic) <MPNowPlayingPlaybackQueueDataSource> *playbackQueueDataSource;
@property (nonatomic) <MPNowPlayingPlaybackQueueDelegate> *playbackQueueDelegate;
@property unsigned long long playbackState;
@property (nonatomic, readonly) NSString *playerID;

+ (id)defaultCenter;
+ (id)infoCenterForPlayerID:(id)arg1;

- (void).cxx_destruct;
- (void)_asynchronousRequests:(void*)arg1 forItem:(id)arg2 mediaRemoteContentItem:(void*)arg3 completion:(id /* block */)arg4;
- (void)_clearPlaybackQueueDataSourceCallbacks;
- (void)_contentItemChangedNotification:(id)arg1;
- (void)_pushContentItemsUpdate;
- (void)_pushNowPlayingInfoAndRetry:(bool)arg1;
- (id)_queryChildItemFromDatasource:(id)arg1 atIndexPath:(id)arg2 fromRoot:(id)arg3;
- (void)_registerLyricsDelegateCallbacks:(id)arg1;
- (void)_registerPlaybackQueueDataSourceCallbacks:(id)arg1;
- (void)_removeToken:(void**)arg1;
- (void)becomeActive;
- (void)beginObservingChangesForContentItemIDs:(id)arg1;
- (void)beginPlaybackQueueContentItemUpdates;
- (void)dealloc;
- (void)endPlaybackQueueContentItemUpdates;
- (id)init;
- (id)initWithPlayerID:(id)arg1;
- (void)invalidatePlaybackQueue;
- (id)lyricsDelegate;
- (id)nowPlayingInfo;
- (id)playbackQueueDataSource;
- (id)playbackQueueDelegate;
- (unsigned long long)playbackState;
- (id)playerID;
- (void)setLyricsDelegate:(id)arg1;
- (void)setNowPlayingInfo:(id)arg1;
- (void)setPlaybackQueueDataSource:(id)arg1;
- (void)setPlaybackQueueDelegate:(id)arg1;
- (void)setPlaybackState:(unsigned long long)arg1;

@end
