/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPPlaybackContext : NSObject <NSCoding> {
    NSString * _playActivityFeatureName;
    NSData * _playActivityRecommendationData;
    long long  _repeatType;
    bool  _shouldRestartPlayback;
    bool  _shouldStartPlayback;
    long long  _shuffleType;
    NSString * _siriReferenceIdentifier;
    long long  _startIndex;
}

@property (nonatomic, copy) NSString *playActivityFeatureName;
@property (nonatomic, copy) NSData *playActivityRecommendationData;
@property (nonatomic) long long repeatType;
@property (nonatomic) bool shouldRestartPlayback;
@property (nonatomic) bool shouldStartPlayback;
@property (nonatomic) long long shuffleType;
@property (nonatomic, copy) NSString *siriReferenceIdentifier;
@property (nonatomic) long long startIndex;

+ (Class)queueFeederClass;

- (void).cxx_destruct;
- (id)description;
- (id)descriptionComponents;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)playActivityFeatureName;
- (id)playActivityRecommendationData;
- (long long)repeatType;
- (void)setPlayActivityFeatureName:(id)arg1;
- (void)setPlayActivityRecommendationData:(id)arg1;
- (void)setRepeatType:(long long)arg1;
- (void)setShouldRestartPlayback:(bool)arg1;
- (void)setShouldStartPlayback:(bool)arg1;
- (void)setShuffleType:(long long)arg1;
- (void)setSiriReferenceIdentifier:(id)arg1;
- (void)setStartIndex:(long long)arg1;
- (bool)shouldRestartPlayback;
- (bool)shouldStartPlayback;
- (long long)shuffleType;
- (id)siriReferenceIdentifier;
- (long long)startIndex;

@end
