/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPRadioStationRemotePlaybackQueue : MPRemotePlaybackQueue {
    long long  _stationID;
    NSString * _stationStringID;
}

@property (nonatomic, readonly) long long stationID;
@property (nonatomic, readonly) NSString *stationStringID;

- (void).cxx_destruct;
- (id)description;
- (id)initWithMediaRemotePlaybackQueue:(struct _MRSystemAppPlaybackQueue { }*)arg1;
- (long long)stationID;
- (id)stationStringID;
- (bool)verifyWithError:(id*)arg1;

@end
