/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@interface SSPaymentSheet : NSObject <NSCopying, SSXPCCoding> {
    NSString * _accountHeader;
    long long  _confirmationTitleType;
    NSString * _countryCode;
    NSString * _currencyCode;
    NSString * _displayPrice;
    NSAttributedString * _displayPriceLabel;
    NSArray * _flexList;
    NSLock * _lock;
    long long  _payeeType;
    NSString * _paymentSummary;
    NSNumber * _price;
    NSString * _ratingHeader;
    NSString * _ratingValue;
    NSURL * _salableIconURL;
    NSString * _salableIconURLString;
    NSArray * _salableInfo;
    NSAttributedString * _salableInfoLabel;
    NSString * _storeName;
    NSString * _title;
    long long  _titleType;
}

@property (copy) NSString *accountHeader;
@property long long confirmationTitleType;
@property (copy) NSString *countryCode;
@property (copy) NSString *currencyCode;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (copy) NSString *displayPrice;
@property (readonly, copy) NSAttributedString *displayPriceLabel;
@property (copy) NSArray *flexList;
@property (readonly) unsigned long long hash;
@property long long payeeType;
@property (copy) NSString *paymentSummary;
@property (copy) NSNumber *price;
@property (copy) NSString *ratingHeader;
@property (copy) NSString *ratingValue;
@property (readonly, copy) NSURL *salableIconURL;
@property (copy) NSString *salableIconURLString;
@property (copy) NSArray *salableInfo;
@property (readonly, copy) NSAttributedString *salableInfoLabel;
@property (copy) NSString *storeName;
@property (readonly) Class superclass;
@property (copy) NSString *title;
@property long long titleType;

- (void).cxx_destruct;
- (id)_attributedStringForString:(id)arg1;
- (id)_attributedStringForStringArray:(id)arg1;
- (long long)_confirmationTitleTypeForStringValue:(id)arg1;
- (id)_displayPriceLabelForDisplayPrice:(id)arg1;
- (void)_init;
- (void)_lock;
- (void)_parseResponse:(id)arg1;
- (long long)_payeeTypeForRequestorValue:(id)arg1;
- (long long)_payeeTypeInferredFromEnumeratedTitle;
- (id)_replaceBreakingSpaceMarkupForMutableAttributedString:(id)arg1;
- (id)_replaceMarkupForMutableAttributedString:(id)arg1 markupType:(long long)arg2;
- (void)_unlock;
- (id)accountHeader;
- (long long)confirmationTitleType;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)copyXPCEncoding;
- (id)countryCode;
- (id)currencyCode;
- (id)displayPrice;
- (id)displayPriceLabel;
- (id)flexList;
- (id)init;
- (id)initWithServerResponse:(id)arg1;
- (id)initWithXPCEncoding:(id)arg1;
- (long long)payeeType;
- (id)paymentSummary;
- (id)price;
- (id)ratingHeader;
- (id)ratingValue;
- (id)salableIconURL;
- (id)salableIconURLString;
- (id)salableInfo;
- (id)salableInfoLabel;
- (void)setAccountHeader:(id)arg1;
- (void)setConfirmationTitleType:(long long)arg1;
- (void)setCountryCode:(id)arg1;
- (void)setCurrencyCode:(id)arg1;
- (void)setDisplayPrice:(id)arg1;
- (void)setFlexList:(id)arg1;
- (void)setPayeeType:(long long)arg1;
- (void)setPaymentSummary:(id)arg1;
- (void)setPrice:(id)arg1;
- (void)setRatingHeader:(id)arg1;
- (void)setRatingValue:(id)arg1;
- (void)setSalableIconURLString:(id)arg1;
- (void)setSalableInfo:(id)arg1;
- (void)setStoreName:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setTitleType:(long long)arg1;
- (id)storeName;
- (id)title;
- (long long)titleType;

@end
