/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@interface SSUpdateAccountResponse : NSObject {
    NSString * _passwordEquivalentToken;
    SSAccount * _updatedAccount;
}

@property (nonatomic, readonly, copy) NSString *passwordEquivalentToken;
@property (nonatomic, readonly) SSAccount *updatedAccount;

- (void).cxx_destruct;
- (id)initWithUpdatedAccount:(id)arg1 passwordEquivalentToken:(id)arg2;
- (id)passwordEquivalentToken;
- (id)updatedAccount;

@end
