/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GraphVisualizer.framework/GraphVisualizer
 */

@interface GVHorizontalLayer : GVLayoutLayer

+ (id)layerWithSeparation:(double)arg1;

- (double)height;
- (void)initializeNodePositions;
- (struct CGSize { double x1; double x2; })sizeForDummy;
- (void)updateNodePositionsBasedOnLayer:(id)arg1;
- (void)updateNodePositionsByCenterLine:(double)arg1;
- (double)width;

@end
