/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GraphVisualizer.framework/GraphVisualizer
 */

@interface GVLayout : NSObject {
    int  direction;
    GVGraph * graph;
    NSMutableArray * layers;
    NSMutableArray * selfEdges;
    struct CGSize { 
        double width; 
        double height; 
    }  separation;
}

@property (nonatomic) int direction;
@property (nonatomic) GVGraph *graph;
@property (nonatomic, retain) NSMutableArray *layers;
@property (nonatomic, retain) NSMutableArray *selfEdges;
@property (nonatomic) struct CGSize { double x1; double x2; } separation;

+ (struct CGSize { double x1; double x2; })layoutGraph:(id)arg1 withDirection:(int)arg2 separation:(struct CGSize { double x1; double x2; })arg3;

- (void)_removeCycleDFS:(id)arg1 visistedNodes:(id)arg2 nodesInStack:(id)arg3;
- (void)assignCoordinates;
- (void)assignLayers;
- (void)dealloc;
- (int)direction;
- (struct CGSize { double x1; double x2; })doLayout:(id)arg1 direction:(int)arg2 separation:(struct CGSize { double x1; double x2; })arg3;
- (id)graph;
- (id)init;
- (void)initializeLayers;
- (void)initializeVertexCoordinates;
- (id)layers;
- (void)orderVertices;
- (void)removeCycles;
- (void)removeSelfEdges;
- (id)selfEdges;
- (struct CGSize { double x1; double x2; })separation;
- (void)setDirection:(int)arg1;
- (void)setGraph:(id)arg1;
- (void)setLayers:(id)arg1;
- (void)setSelfEdges:(id)arg1;
- (void)setSeparation:(struct CGSize { double x1; double x2; })arg1;
- (void)undoRemoveCycles;
- (void)undoRemoveSelfEdges;

@end
