/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CommonUtilities.framework/CommonUtilities
 */

@interface CUTCheckpointRange : CUTCheckpoint {
    NSDate * _endDate;
    bool  _ordered;
    NSDate * _startDate;
}

@property (nonatomic, retain) NSDate *endDate;
@property (getter=isOrdered, nonatomic) bool ordered;
@property (nonatomic, retain) NSDate *startDate;

- (void).cxx_destruct;
- (id)description;
- (id)descriptionWithDate:(id*)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)endDate;
- (id)initWithCoder:(id)arg1;
- (id)initWithName:(id)arg1;
- (id)initWithName:(id)arg1 startDate:(id)arg2 endDate:(id)arg3;
- (bool)isOrdered;
- (void)measure:(id /* block */)arg1;
- (void)mergeWithCheckpoint:(id)arg1;
- (void)setEndDate:(id)arg1;
- (void)setOrdered:(bool)arg1;
- (void)setStartDate:(id)arg1;
- (id)startDate;
- (void)touchEndDate;
- (void)touchStartDate;

@end
