/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CommonUtilities.framework/CommonUtilities
 */

@interface CUTCheckpointTrace : NSObject <NSSecureCoding> {
    NSArray * _allCheckpointLayers;
    NSString * _identifier;
    NSString * _name;
    NSDate * _startDate;
}

@property (nonatomic, readonly) NSArray *allCheckpointLayers;
@property (nonatomic, readonly) id currentLayer;
@property (nonatomic, readonly) NSString *identifier;
@property (nonatomic, readonly) NSString *name;
@property (nonatomic, readonly) NSDate *startDate;

+ (id)pendingCheckpoints;
+ (void)registerPendingCheckpoint;
+ (bool)supportsSecureCoding;
+ (void)unregisterFinishedCheckpoint;

- (void).cxx_destruct;
- (id)allCheckpointLayers;
- (id)currentLayer;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)identifier;
- (id)initWithCoder:(id)arg1;
- (id)initWithName:(id)arg1 startDate:(id)arg2 identifier:(id)arg3 allCheckpointLayers:(id)arg4;
- (id)initWithName:(id)arg1 startDate:(id)arg2 identifier:(id)arg3 currentLayer:(id)arg4;
- (id)name;
- (id)startDate;
- (id)traceByPushingLayer:(id)arg1;

@end
