/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CommonUtilities.framework/CommonUtilities
 */

@interface CUTLog : NSObject

+ (id)fileCopier;
+ (id)network;
+ (id)power;
+ (id)weakLink;
+ (id)xpc;

@end
