/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
 */

@interface CloudAppAvailabilityController : NSObject <LSApplicationWorkspaceObserverProtocol> {
    LSApplicationWorkspace * _applicationWorkspace;
    bool  _musicAppRemoved;
    bool  _systemMusicAppPresent;
    bool  _systemVideoAppPresent;
    bool  _tvAppRemoved;
    bool  _videosAppRemoved;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (getter=isSystemMusicAppPresent, nonatomic, readonly) bool systemMusicAppPresent;
@property (getter=isSystemVideoAppPresent, nonatomic, readonly) bool systemVideoAppPresent;

+ (id)sharedController;

- (void).cxx_destruct;
- (bool)_isMusicAppBundleID:(id)arg1;
- (bool)_isTVAppBundleID:(id)arg1;
- (bool)_isVideosAppBundleID:(id)arg1;
- (id)init;
- (bool)isSystemMusicAppPresent;
- (bool)isSystemVideoAppPresent;
- (void)processAddedSystemAppBundle:(id)arg1;
- (void)processRemovedSystemAppBundle:(id)arg1;

@end
