/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchFoundation.framework/SearchFoundation
 */

@interface SFCardViewAppearFeedback : SFFeedback {
    SFCard * _card;
}

@property (nonatomic, retain) SFCard *card;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)card;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCard:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)setCard:(id)arg1;

@end
