/* Generated by RuntimeBrowser
   Image: /usr/lib/libAudioStatistics.dylib
 */

@interface CAReporter : NSObject {
    long long  _reporterID;
    unsigned short  _serviceType;
}

@property (readonly) long long reporterID;
@property (nonatomic) unsigned short serviceType;

+ (void)sendSingleMessage:(id)arg1 category:(unsigned short)arg2 type:(unsigned short)arg3;

- (void)cacheServiceType:(unsigned short)arg1;
- (id)init;
- (id)initWithNewReporterID;
- (id)initWithReporterID:(long long)arg1;
- (id)initWithReporterID:(long long)arg1 serviceType:(unsigned short)arg2;
- (long long)reporterID;
- (void)sendMessage:(id)arg1 category:(unsigned short)arg2 type:(unsigned short)arg3;
- (unsigned short)serviceType;
- (void)setServiceType:(unsigned short)arg1;
- (void)start;
- (void)stop;
- (void)updateWithReporterID:(long long)arg1;

@end
