/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface _INConcreteParameter : NSObject <INParameter, NSSecureCoding> {
    <_INConcreteParameterDataSource> * _dataSource;
    NSMutableDictionary * _indexesForSubKeyPaths;
    NSString * _parameterKeyPath;
}

@property (nonatomic) <_INConcreteParameterDataSource> *dataSource;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSMutableDictionary *indexesForSubKeyPaths;
@property (nonatomic, copy) NSString *parameterKeyPath;
@property (nonatomic, readonly) id parameterValue;
@property (nonatomic, readonly) id parameterizedObject;
@property (readonly) Class superclass;

+ (id)_innerConcreteParameterWithDataSource:(id)arg1 parameterKeyPath:(id)arg2;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_dictionaryRepresentation;
- (id)_sanitizedKeyPathForKeyPath:(id)arg1;
- (id)_valueOfObject:(id)arg1 forRemainingKeyPath:(id)arg2 inFullyQualifiedKeyPath:(id)arg3;
- (id)dataSource;
- (id)description;
- (id)descriptionAtIndent:(unsigned long long)arg1;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (unsigned long long)indexForSubKeyPath:(id)arg1;
- (id)indexesForSubKeyPaths;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToParameter:(id)arg1;
- (id)parameterKeyPath;
- (id)parameterValue;
- (id)parameterizedObject;
- (void)setDataSource:(id)arg1;
- (void)setIndex:(unsigned long long)arg1 forSubKeyPath:(id)arg2;
- (void)setIndexesForSubKeyPaths:(id)arg1;
- (void)setParameterKeyPath:(id)arg1;

@end
