/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface INCallDestinationTypeResolutionResult : INIntentResolutionResult

+ (id)confirmationRequiredWithValueToConfirm:(long long)arg1;
+ (id)successWithResolvedValue:(long long)arg1;

@end
