/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface INIntentParameter : NSObject <INParameter, NSSecureCoding, _INConcreteParameterDataSource> {
    _INConcreteParameter * _innerConcreteParameter;
    INIntent * _parameterizedIntent;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (getter=_innerConcreteParameter, setter=_setInnerConcreteParameter:, nonatomic, retain) _INConcreteParameter *innerConcreteParameter;
@property (nonatomic, readonly, copy) NSString *parameterKeyPath;
@property (nonatomic, readonly) id parameterValue;
@property (nonatomic, readonly) INIntent *parameterizedIntent;
@property (nonatomic, readonly) id parameterizedObject;
@property (readonly) Class superclass;

+ (id)intentParameterWithIntent:(id)arg1 parameterKeyPath:(id)arg2;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_dictionaryRepresentation;
- (id)_innerConcreteParameter;
- (id)_parameterizedObjectForConcreteParameter:(id)arg1;
- (void)_setInnerConcreteParameter:(id)arg1;
- (void)_setParameterizedIntent:(id)arg1;
- (id)description;
- (id)descriptionAtIndent:(unsigned long long)arg1;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (unsigned long long)indexForSubKeyPath:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToParameter:(id)arg1;
- (id)parameterKeyPath;
- (id)parameterValue;
- (id)parameterizedIntent;
- (id)parameterizedObject;
- (void)setIndex:(unsigned long long)arg1 forSubKeyPath:(id)arg2;

@end
