/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface INParameter : NSObject <INParameter, NSObject, NSSecureCoding> {
    NSMutableDictionary * _indexesForSubKeyPaths;
    Class  _parameterClass;
    NSString * _parameterKeyPath;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSMutableDictionary *indexesForSubKeyPaths;
@property (nonatomic, retain) Class parameterClass;
@property (nonatomic, copy) NSString *parameterKeyPath;
@property (nonatomic, readonly) id parameterValue;
@property (nonatomic, readonly) id parameterizedObject;
@property (readonly) Class superclass;

+ (id)parameterForClass:(Class)arg1 keyPath:(id)arg2;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_dictionaryRepresentation;
- (id)_parameterValueForParameterizedObject:(id)arg1;
- (id)_sanitizedKeyPathForKeyPath:(id)arg1;
- (id)_valueOfObject:(id)arg1 forRemainingKeyPath:(id)arg2 inFullyQualifiedKeyPath:(id)arg3;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (unsigned long long)indexForSubKeyPath:(id)arg1;
- (id)indexesForSubKeyPaths;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToParameter:(id)arg1;
- (Class)parameterClass;
- (id)parameterKeyPath;
- (id)parameterValue;
- (id)parameterizedObject;
- (void)setIndex:(unsigned long long)arg1 forSubKeyPath:(id)arg2;
- (void)setIndexesForSubKeyPaths:(id)arg1;
- (void)setParameterClass:(Class)arg1;
- (void)setParameterKeyPath:(id)arg1;

@end
