/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

@interface ISLogoutOperation : ISOperation {
    ACAccount * _account;
}

@property (nonatomic, retain) ACAccount *account;

- (void).cxx_destruct;
- (id)account;
- (id)initWithAccount:(id)arg1;
- (void)run;
- (void)setAccount:(id)arg1;

@end
