/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DocumentManagerCore.framework/DocumentManagerCore
 */

@interface DOCTagRegistrySpotlightDataSource : NSObject {
    <DOCTagRegistryDelegate> * _delegate;
    NSMutableDictionary * _discoveredTags;
    CSSearchQuery * _query;
}

@property (nonatomic) <DOCTagRegistryDelegate> *delegate;
@property (nonatomic, retain) NSMutableDictionary *discoveredTags;
@property (nonatomic, retain) CSSearchQuery *query;

- (void).cxx_destruct;
- (id)delegate;
- (id)discoveredTags;
- (id)initWithDelegate:(id)arg1;
- (void)postNotification;
- (id)query;
- (void)setDelegate:(id)arg1;
- (void)setDiscoveredTags:(id)arg1;
- (void)setQuery:(id)arg1;

@end
