/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface WebAVAudioSessionAvailableInputsListener : NSObject {
    struct function<void ()>="__buf_"{type="__lx"[24C] {}  _callback;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithCallback:(struct function<void ()>={type=[24C] {})arg1;
- (void)invalidate;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;

@end
