/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface _MKAnnotationViewPair : NSObject {
    MKAnnotationView * _first;
    MKAnnotationView * _second;
}

@property (nonatomic, retain) MKAnnotationView *first;
@property (nonatomic, retain) MKAnnotationView *second;

- (void)dealloc;
- (id)first;
- (unsigned long long)hash;
- (id)initWithFirst:(id)arg1 second:(id)arg2;
- (bool)isEqual:(id)arg1;
- (id)second;
- (void)setFirst:(id)arg1;
- (void)setSecond:(id)arg1;

@end
