/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface _MXIntentResponseObserverProxy : NSObject <INIntentResponseObserver> {
    <_MXIntentResponseObserver> * _observer;
}

@property (nonatomic) <_MXIntentResponseObserver> *observer;

- (void).cxx_destruct;
- (void)didReceiveError:(id)arg1;
- (id)initWithObserver:(id)arg1;
- (void)intentResponseDidUpdate:(id)arg1;
- (id)observer;
- (void)setObserver:(id)arg1;
- (void)stopObserving;

@end
