/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKPlaceHoursDayRow : MKPlaceSectionRowView {
    NSArray * _baselineToBaseline;
    NSLayoutConstraint * _baselineToBottom;
    double  _baselineToBottomConstant;
    NSLayoutConstraint * _baselineToTop;
    NSArray * _labels;
}

@property (nonatomic) double baselineToBottomConstant;

- (void).cxx_destruct;
- (void)_contentSizeDidChange;
- (id)_standardLabel;
- (double)baselineToBottomConstant;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setBaselineToBottomConstant:(double)arg1;
- (void)setDays:(id)arg1 hours:(id)arg2 shouldStack:(bool)arg3;
- (bool)wantsDefaultClipping;

@end
