/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKSpatialCollider : NSObject <NSFastEnumeration> {
    NSMutableOrderedSet * _horViews;
    long long  _options;
    NSSet * _preColls;
    NSMutableSet * _regColls;
    NSMutableOrderedSet * _verViews;
}

+ (id /* block */)_horSortComparator;
+ (id /* block */)_verSortComparator;

- (id)annotationViewAtIndex:(unsigned long long)arg1;
- (unsigned long long)countByEnumeratingWithState:(struct { unsigned long long x1; id *x2; unsigned long long x3; unsigned long long x4[5]; }*)arg1 objects:(id*)arg2 count:(unsigned long long)arg3;
- (void)dealloc;
- (id)initWithAnnotationViews:(id)arg1 previousCollissions:(id)arg2 options:(long long)arg3;
- (void)insertAnnotationView:(id)arg1;
- (id)registeredCollissions;
- (unsigned long long)viewCount;
- (id)viewsCollidingWithAnnotationView:(id)arg1;

@end
