/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Navigation.framework/Navigation
 */

@interface MNNavigationDetailsRouteInfo : NSObject {
    unsigned long long  _alternateRouteIndex;
    NSDate * _displayETA;
    unsigned long long  _displayRemainingMinutes;
    GEOComposedRoute * _route;
}

@property (nonatomic) unsigned long long alternateRouteIndex;
@property (nonatomic, retain) NSDate *displayETA;
@property (nonatomic) unsigned long long displayRemainingMinutes;
@property (nonatomic, retain) GEOComposedRoute *route;

- (void).cxx_destruct;
- (unsigned long long)alternateRouteIndex;
- (id)displayETA;
- (unsigned long long)displayRemainingMinutes;
- (id)route;
- (void)setAlternateRouteIndex:(unsigned long long)arg1;
- (void)setDisplayETA:(id)arg1;
- (void)setDisplayRemainingMinutes:(unsigned long long)arg1;
- (void)setRoute:(id)arg1;

@end
