/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Navigation.framework/Navigation
 */

@interface MNTimeManager : NSObject {
    <MNTimeProvider> * _provider;
}

@property (nonatomic, retain) <MNTimeProvider> *provider;

+ (id)currentDate;
+ (double)currentTime;
+ (id)sharedManager;

- (void).cxx_destruct;
- (void)_resetToDefaultProvider;
- (id)init;
- (id)provider;
- (void)setProvider:(id)arg1;

@end
