/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreSpotlight.framework/CoreSpotlight
 */

@interface CSSearchableItem : NSObject <CSIndexQueuableItem, NSCopying, NSFileProviderItem_Private, NSSecureCoding> {
    CSSearchableItemAttributeSet * _attributeSet;
}

@property (retain) CSSearchableItemAttributeSet *attributeSet;
@property (copy) NSString *bundleID;
@property (nonatomic, readonly) unsigned long long capabilities;
@property (nonatomic, readonly, copy) NSNumber *childItemCount;
@property (readonly, copy) NSString *containerDisplayName;
@property (nonatomic, readonly, copy) NSDate *contentModificationDate;
@property (nonatomic, readonly, copy) NSDate *creationDate;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSString *displayName;
@property (nonatomic, readonly, copy) NSNumber *documentSize;
@property (copy) NSString *domainIdentifier;
@property (getter=isDownloadRequested, readonly, copy) NSNumber *downloadRequested;
@property (getter=isDownloaded, nonatomic, readonly) bool downloaded;
@property (getter=isDownloading, nonatomic, readonly) bool downloading;
@property (nonatomic, readonly, copy) NSError *downloadingError;
@property (copy) NSDate *expirationDate;
@property (nonatomic, readonly, copy) NSNumber *favoriteRank;
@property (readonly, copy) NSURL *fileURL;
@property (nonatomic, readonly, copy) NSString *filename;
@property (readonly) NSString *fp_domainIdentifier;
@property (readonly) NSString *fp_spotlightDomainIdentifier;
@property (readonly, copy) NSNumber *hasUnresolvedConflicts;
@property (readonly) unsigned long long hash;
@property (getter=isHidden, readonly) bool hidden;
@property bool isUpdate;
@property (nonatomic, readonly, copy) NSString *itemIdentifier;
@property (nonatomic, readonly, copy) NSDate *lastUsedDate;
@property (nonatomic, readonly) NSPersonNameComponents *mostRecentEditorNameComponents;
@property (getter=isMostRecentVersionDownloaded, nonatomic, readonly) bool mostRecentVersionDownloaded;
@property bool noIndex;
@property (nonatomic, readonly) NSPersonNameComponents *ownerNameComponents;
@property (nonatomic, readonly, copy) NSString *parentItemIdentifier;
@property (copy) NSString *protection;
@property (readonly) NSString *providerIdentifier;
@property (getter=isShared, nonatomic, readonly) bool shared;
@property (getter=isSharedByCurrentUser, nonatomic, readonly) bool sharedByCurrentUser;
@property (readonly) NSString *sharingPermissions;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) NSData *tagData;
@property (getter=isTrashed, nonatomic, readonly) bool trashed;
@property (nonatomic, readonly, copy) NSString *typeIdentifier;
@property (copy) NSString *uniqueIdentifier;
@property (getter=isUploaded, nonatomic, readonly) bool uploaded;
@property (getter=isUploading, nonatomic, readonly) bool uploading;
@property (nonatomic, readonly, copy) NSError *uploadingError;
@property (nonatomic, readonly) NSDictionary *userInfo;
@property (nonatomic, readonly) NSData *versionIdentifier;

// Image: /System/Library/Frameworks/CoreSpotlight.framework/CoreSpotlight

+ (id)searchableItemFromUserActivity:(id)arg1 bundleID:(id)arg2;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)_fixBrokenAuthorNames:(id)arg1;
- (bool)_hasAttributesOfType:(id)arg1;
- (bool)_isFullyFormed;
- (void)_populateMissingPeopleWithNames:(id)arg1 emailAddresses:(id)arg2 allItemPersons:(id)arg3 primaryItemPersons:(id)arg4 additionalItemPersons:(id)arg5 hiddenAdditionalItemPersons:(id)arg6 personDictionary:(id)arg7 contactProperties:(id)arg8 nameKey:(id)arg9 emailKey:(id)arg10 contactIdentifierKey:(id)arg11 personKey:(id)arg12 attributeSet:(id)arg13;
- (id)_propertiesDescription;
- (void)_standardizeDeprecatedProperties:(id)arg1;
- (void)_standardizeHTML:(id)arg1;
- (void)_standardizeMarkAs:(id)arg1;
- (void)_standardizePeople:(id)arg1;
- (void)_updateWithSearchableItem:(id)arg1;
- (id)attributeSet;
- (id)attributes;
- (void)breakOutPersonInformationInSet:(id)arg1 withName:(id)arg2 emails:(id)arg3 contactIdentifiers:(id)arg4 nameKey:(id)arg5 emailKey:(id)arg6 contactIdentifierKey:(id)arg7 emailAddressKey:(id)arg8 attributeSet:(id)arg9;
- (id)bundleID;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)debugDescription;
- (id)description;
- (id)domainIdentifier;
- (void)encodeWithCoder:(id)arg1;
- (id)expirationDate;
- (id)filteredSpotlightAttributes;
- (unsigned long long)hash;
- (id)init;
- (id)initWithAttributeSet:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithUniqueIdentifier:(id)arg1 domainIdentifier:(id)arg2 attributeSet:(id)arg3;
- (bool)isEqual:(id)arg1;
- (bool)isUpdate;
- (bool)noIndex;
- (id)protection;
- (id)searchableItem;
- (void)setAttributeSet:(id)arg1;
- (void)setAttributes:(id)arg1;
- (void)setBundleID:(id)arg1;
- (void)setDomainIdentifier:(id)arg1;
- (void)setExpirationDate:(id)arg1;
- (void)setIsUpdate:(bool)arg1;
- (void)setNoIndex:(bool)arg1;
- (void)setProtection:(id)arg1;
- (void)setUniqueIdentifier:(id)arg1;
- (void)standardizeAttributes;
- (id)uniqueIdentifier;

// Image: /System/Library/Frameworks/FileProvider.framework/FileProvider

+ (id)fp_queryFetchAttributes;

- (unsigned long long)capabilities;
- (id)childItemCount;
- (id)containerSubitemCount;
- (id)contentModificationDate;
- (id)creationDate;
- (id)displayName;
- (id)documentSize;
- (id)downloadingError;
- (id)favoriteRank;
- (id)filename;
- (id)fp_domainIdentifier;
- (id)fp_spotlightDomainIdentifier;
- (bool)isDownloaded;
- (bool)isDownloading;
- (bool)isMostRecentVersionDownloaded;
- (bool)isShared;
- (bool)isSharedByCurrentUser;
- (bool)isTrashed;
- (bool)isUploaded;
- (bool)isUploading;
- (id)itemIdentifier;
- (id)lastUsedDate;
- (id)mostRecentEditorNameComponents;
- (id)ownerNameComponents;
- (id)parentItemIdentifier;
- (id)providerIdentifier;
- (id)sharingCurrentUserPermissions;
- (id)sharingCurrentUserRole;
- (id)tagData;
- (id)typeIdentifier;
- (id)uploadingError;
- (id)userInfo;
- (id)versionIdentifier;

// Image: /System/Library/PrivateFrameworks/ContactsUICore.framework/ContactsUICore

- (id)_cnui_valueForAttribute:(id)arg1;

@end
