/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@interface _MTLIndirectArgumentEncoder : NSObject {
    <MTLDevice> * _device;
    NSString * _label;
    _MTLIndirectArgumentBufferLayout * _layout;
}

@property (nonatomic, readonly) <MTLDevice> *device;
@property (copy) NSString *label;
@property (nonatomic, readonly) _MTLIndirectArgumentBufferLayout *layout;

- (void)dealloc;
- (id)device;
- (id)initWithLayout:(id)arg1 device:(id)arg2;
- (id)label;
- (id)layout;
- (id)newIndirectArgumentEncoderForBufferAtIndex:(unsigned long long)arg1;
- (void)setLabel:(id)arg1;

@end
