/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@interface MTLPointerTypeInternal : MTLPointerType {
    unsigned long long  _access;
    unsigned long long  _alignment;
    unsigned long long  _dataSize;
    unsigned long long  _dataType;
    bool  _elementIsIndirectArgumentBuffer;
    unsigned long long  _elementType;
    MTLType * _elementTypeDescription;
}

- (unsigned long long)access;
- (unsigned long long)alignment;
- (unsigned long long)dataSize;
- (unsigned long long)dataType;
- (void)dealloc;
- (bool)elementIsIndirectArgumentBuffer;
- (unsigned long long)elementType;
- (id)elementTypeDescription;
- (id)formattedDescription:(unsigned long long)arg1;
- (id)initWithElementType:(unsigned long long)arg1 elementTypeDescription:(id)arg2 access:(unsigned long long)arg3 alignment:(unsigned long long)arg4 dataSize:(unsigned long long)arg5 elementIsIndirectArgumentBuffer:(bool)arg6;

@end
