/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Metal.framework/Metal
 */

@interface MTLPointerType : MTLType

@property (readonly) unsigned long long access;
@property (readonly) unsigned long long alignment;
@property (readonly) unsigned long long dataSize;
@property (readonly) bool elementIsIndirectArgumentBuffer;
@property (readonly) unsigned long long elementType;
@property (readonly) MTLType *elementTypeDescription;

+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;

@end
