/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SceneKit.framework/SceneKit
 */

@interface SCNGeometrySubdivisionSurfaceTessellator : SCNGeometryTessellatorLegacy

@property (nonatomic) unsigned long long subdivisionLevel;
@property (nonatomic) unsigned long long tessellationLevel;
@property (nonatomic) bool useScreenSpaceTessellation;
@property (nonatomic) bool wantsAdaptiveSubdivision;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;
- (bool)restrictsToSingleCrease;
- (void)setRestrictsToSingleCrease:(bool)arg1;
- (void)setSubdivisionLevel:(unsigned long long)arg1;
- (void)setTessellationLevel:(unsigned long long)arg1;
- (void)setUseScreenSpaceTessellation:(bool)arg1;
- (void)setWantsAdaptiveSubdivision:(bool)arg1;
- (unsigned long long)subdivisionLevel;
- (unsigned long long)tessellationLevel;
- (bool)useScreenSpaceTessellation;
- (bool)wantsAdaptiveSubdivision;

@end
