/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SceneKit.framework/SceneKit
 */

@interface SCNGeometryConstrainedEdgeLengthTessellator : SCNGeometryTessellatorLegacy

@property (nonatomic) double maximumEdgeLength;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;
- (double)maximumEdgeLength;
- (void)setMaximumEdgeLength:(double)arg1;

@end
