/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SceneKit.framework/SceneKit
 */

@interface SCNGeometryConstantTessellator : SCNGeometryTessellatorLegacy

@property (nonatomic) double edgeTessellationFactor;
@property (nonatomic) double insideTessellationFactor;
@property (nonatomic) unsigned long long tessellationPartitionMode;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (double)edgeTessellationFactor;
- (id)init;
- (double)insideTessellationFactor;
- (void)setEdgeTessellationFactor:(double)arg1;
- (void)setInsideTessellationFactor:(double)arg1;
- (void)setTessellationPartitionMode:(unsigned long long)arg1;
- (unsigned long long)tessellationPartitionMode;

@end
