/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SceneKit.framework/SceneKit
 */

@interface SCNGeometryTessellatorLegacy : NSObject <NSCopying, NSSecureCoding> {
    NSMutableSet * _clients;
    struct { 
        unsigned char type; 
        float tessellationFactorScale; 
        unsigned int tessellationPartitionMode; 
        unsigned char tessellationSmoothingMode; 
        union { 
            struct { 
                float edgeTessellationFactor; 
                float insideTessellationFactor; 
            } uniform; 
            struct { 
                float projectedEdgeLength; 
            } screenSpaceAdaptive; 
            struct { 
                float maximumEdgeLength; 
            } constrainedEdgeLength; 
            struct { 
                unsigned char tessellationLevel; 
                unsigned int restrictsToSingleCrease : 1; 
                unsigned int useScreenSpaceTessellation : 1; 
            } subdivisionSurface; 
        } parameters; 
    }  _tessellatorValue;
}

+ (bool)supportsSecureCoding;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithTessellatorValue:(struct { unsigned char x1; float x2; unsigned int x3; unsigned char x4; union { struct { float x_1_2_1; float x_1_2_2; } x_5_1_1; struct { float x_2_2_1; } x_5_1_2; struct { float x_3_2_1; } x_5_1_3; struct { unsigned char x_4_2_1; unsigned int x_4_2_2 : 1; unsigned int x_4_2_3 : 1; } x_5_1_4; } x5; })arg1;
- (void)setTessellatorValue:(struct { unsigned char x1; float x2; unsigned int x3; unsigned char x4; union { struct { float x_1_2_1; float x_1_2_2; } x_5_1_1; struct { float x_2_2_1; } x_5_1_2; struct { float x_3_2_1; } x_5_1_3; struct { unsigned char x_4_2_1; unsigned int x_4_2_2 : 1; unsigned int x_4_2_3 : 1; } x_5_1_4; } x5; })arg1;
- (struct { unsigned char x1; float x2; unsigned int x3; unsigned char x4; union { struct { float x_1_2_1; float x_1_2_2; } x_5_1_1; struct { float x_2_2_1; } x_5_1_2; struct { float x_3_2_1; } x_5_1_3; struct { unsigned char x_4_2_1; unsigned int x_4_2_2 : 1; unsigned int x_4_2_3 : 1; } x_5_1_4; } x5; })tessellatorValue;
- (void)tessellatorValueDidChange;
- (void)tessellatorValueDidChangeForClient:(id)arg1;

@end
