/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/FileProvider.framework/libFileProviderExtension.dylib
 */

@interface _FPPageSortedByName : NSData

- (const void*)bytes;
- (unsigned long long)length;

@end
