/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iTunesCloud.framework/iTunesCloud
 */

@interface ICSuzeLeaseSession : NSObject {
    NSObject<OS_dispatch_queue> * _calloutQueue;
    ICSuzeLeaseSessionConfiguration * _configuration;
    <ICSuzeLeaseSessionDelegate> * _delegate;
    bool  _isRunning;
    NSObject<OS_dispatch_source> * _leaseRenewTimer;
    ICFPLeaseSyncSession * _leaseSyncSession;
    NSOperationQueue * _operationQueue;
}

@property (nonatomic, readonly, copy) ICSuzeLeaseSessionConfiguration *configuration;
@property (nonatomic) <ICSuzeLeaseSessionDelegate> *delegate;

- (void).cxx_destruct;
- (id)_newSuzeLeaseRequestWithType:(long long)arg1 clientData:(id)arg2;
- (void)_renewLeaseTimerAction;
- (void)_updateRenewalTimerWithResponse:(id)arg1;
- (id)configuration;
- (void)dealloc;
- (id)delegate;
- (id)initWithConfiguration:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)startLeaseSessionWithCompletionHandler:(id /* block */)arg1;
- (void)stopLeaseSessionWithCompletionHandler:(id /* block */)arg1;

@end
