/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iTunesCloud.framework/iTunesCloud
 */

@interface ICURLBagCacheEntry : NSObject {
    double  _expriationTime;
    ICURLBag * _urlBag;
}

@property (nonatomic) double expriationTime;
@property (retain) ICURLBag *urlBag;

- (void).cxx_destruct;
- (double)expriationTime;
- (id)initWithURLBag:(id)arg1 expirationTime:(double)arg2;
- (void)setExpriationTime:(double)arg1;
- (void)setUrlBag:(id)arg1;
- (id)urlBag;

@end
