/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iTunesCloud.framework/iTunesCloud
 */

@interface ICUserIdentityStoreACAccountBackend : NSObject <ICUserIdentityStoreBackend> {
    ACAccountStore * _accountStore;
}

@property (nonatomic, copy) NSNumber *activeAccountDSID;
@property (nonatomic, copy) NSNumber *activeLockerAccountDSID;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) ICUserVerificationContext *verificationContextToEstablishAccount;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)_applyIdentityProperties:(id)arg1 toAccount:(id)arg2;
- (id)activeAccountDSID;
- (id)activeLockerAccountDSID;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)identityPropertiesForDSID:(id)arg1;
- (id)init;
- (id)initWithACAccountStore:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)removeIdentityForDSID:(id)arg1 withCompletionHandler:(id /* block */)arg2;
- (void)replaceIdentityProperties:(id)arg1 forDSID:(id)arg2 withCompletionHandler:(id /* block */)arg3;
- (void)setActiveAccountDSID:(id)arg1;
- (void)setActiveLockerAccountDSID:(id)arg1;
- (void)setIdentityProperties:(id)arg1 forDSID:(id)arg2 withCompletionHandler:(id /* block */)arg3;
- (void)synchronize;
- (id)verificationContextForDSID:(id)arg1;
- (id)verificationContextToEstablishAccount;

@end
