/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIKernelLibrary : NSObject {
    NSObject<OS_dispatch_data> * _data;
}

+ (id)libraryWithData:(id)arg1 error:(id*)arg2;

- (void)dealloc;
- (id)initWithData:(id)arg1 error:(id*)arg2;
- (id)newFunctionWithName:(id)arg1 device:(id)arg2;

@end
