/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIRenderInfo : NSObject {
    void * _priv;
}

@property (readonly) double kernelExecutionTime;
@property (readonly) long long kernelPixelsProcessed;
@property (readonly) long long passCount;

+ (id)renderInfoWithCompletedTask:(id)arg1;

- (id)_pdfDataRepresentation;
- (void)dealloc;
- (id)description;
- (id)initWithCompletedTask:(id)arg1;
- (double)kernelExecutionTime;
- (long long)kernelPixelsProcessed;
- (long long)passCount;

@end
