/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface myDelegatesForEventTest : NSObject <NSStreamDelegate, NSURLSessionTaskDelegate> {
    bool  _eventRec;
    NSInputStream * _inStream;
    NSOutputStream * _outStream;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void)URLSession:(id)arg1 streamTask:(id)arg2 didBecomeInputStream:(id)arg3 outputStream:(id)arg4;
- (void)closeStreams;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;

@end
