/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRAVReconnaissanceSession : NSObject {
    id /* block */  _callback;
    MRAVRoutingDiscoverySession * _discoverySession;
    id  _discoverySessionCallbackToken;
    NSMutableSet * _matchingDevicesFound;
    NSSet * _matchingOutputDeviceUIDsSet;
    bool  _searchInProgress;
    NSTimer * _timeoutTimer;
    MRAVEndpoint * _unanimousEndpoint;
}

@property (nonatomic, copy) id /* block */ callback;
@property (nonatomic, retain) MRAVRoutingDiscoverySession *discoverySession;
@property (nonatomic, retain) id discoverySessionCallbackToken;
@property (nonatomic, retain) NSMutableSet *matchingDevicesFound;
@property (nonatomic, readonly) NSArray *matchingOutputDeviceUIDs;
@property (nonatomic, retain) NSSet *matchingOutputDeviceUIDsSet;
@property (nonatomic) bool searchInProgress;
@property (nonatomic, retain) NSTimer *timeoutTimer;
@property (nonatomic, retain) MRAVEndpoint *unanimousEndpoint;

- (void)_concludeSearch;
- (void)_discoverySessionEndpointsChangedCallback:(id)arg1;
- (void)_endSearch;
- (void)_timeoutTimerFired:(id)arg1;
- (void)beginSearchWithTimeout:(double)arg1 completion:(id /* block */)arg2;
- (id /* block */)callback;
- (void)cancelSearch;
- (void)dealloc;
- (id)discoverySession;
- (id)discoverySessionCallbackToken;
- (id)initWithOutputDeviceUIDs:(id)arg1;
- (id)matchingDevicesFound;
- (id)matchingOutputDeviceUIDs;
- (id)matchingOutputDeviceUIDsSet;
- (bool)searchInProgress;
- (void)setCallback:(id /* block */)arg1;
- (void)setDiscoverySession:(id)arg1;
- (void)setDiscoverySessionCallbackToken:(id)arg1;
- (void)setMatchingDevicesFound:(id)arg1;
- (void)setMatchingOutputDeviceUIDsSet:(id)arg1;
- (void)setSearchInProgress:(bool)arg1;
- (void)setTimeoutTimer:(id)arg1;
- (void)setUnanimousEndpoint:(id)arg1;
- (id)timeoutTimer;
- (id)unanimousEndpoint;

@end
