/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRNowPlayingPlayerClient : NSObject {
    id /* block */  _audioAmplitudeSamplesCallback;
    bool  _coalescingInvalidations;
    NSMutableDictionary * _commandHandlerBlocks;
    double  _invalidatationTimestamp;
    int  _notifyRestoreClientStateForLaunch;
    MRNowPlayingArtwork * _nowPlayingArtwork;
    NSDictionary * _nowPlayingInfo;
    MRPlaybackQueuePlayerClient * _playbackQueueClient;
    unsigned int  _playbackState;
    void * _playerPath;
    NSObject<OS_dispatch_queue> * _serialQueue;
    NSArray * _supportedCommands;
    id /* block */  _videoThumbnailsCallback;
}

@property (nonatomic, copy) id /* block */ audioAmplitudeSamplesCallback;
@property (nonatomic, readonly, copy) NSArray *commandHandlerBlocks;
@property (nonatomic) double invalidatationTimestamp;
@property (nonatomic, retain) MRNowPlayingArtwork *nowPlayingArtwork;
@property (nonatomic, copy) NSDictionary *nowPlayingInfo;
@property (nonatomic, readonly) MRPlaybackQueuePlayerClient *playbackQueueClient;
@property (nonatomic) unsigned int playbackState;
@property (nonatomic, readonly) void*playerPath;
@property (nonatomic, copy) NSArray *supportedCommands;
@property (nonatomic, copy) id /* block */ videoThumbnailsCallback;

- (void)addCommandHandlerBlock:(id /* block */)arg1 forKey:(id)arg2;
- (id /* block */)audioAmplitudeSamplesCallback;
- (id)commandHandlerBlocks;
- (void)dealloc;
- (id)description;
- (id)initWithPlayerPath:(void*)arg1;
- (double)invalidatationTimestamp;
- (id)nowPlayingArtwork;
- (id)nowPlayingInfo;
- (id)playbackQueueClient;
- (unsigned int)playbackState;
- (void*)playerPath;
- (void)removeCommandHandlerBlockForKey:(id)arg1;
- (void)setAudioAmplitudeSamplesCallback:(id /* block */)arg1;
- (void)setInvalidatationTimestamp:(double)arg1;
- (void)setNowPlayingArtwork:(id)arg1;
- (void)setNowPlayingInfo:(id)arg1;
- (void)setPlaybackState:(unsigned int)arg1;
- (void)setSupportedCommands:(id)arg1;
- (void)setVideoThumbnailsCallback:(id /* block */)arg1;
- (id)supportedCommands;
- (bool)testAndSetCoalescingInvalidations;
- (void)unsetCoalescingInvalidations;
- (id /* block */)videoThumbnailsCallback;

@end
