/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRNowPlayingClient : NSObject {
    void * _activePlayer;
    void * _activePlayerPath;
    void * _client;
    int  _notifyRestoreClientStateForLaunch;
    NSArray * _nowPlayingClients;
    NSMutableArray * _playerClients;
    NSObject<OS_dispatch_queue> * _serialQueue;
}

@property (nonatomic) void*activePlayerPath;
@property (nonatomic, readonly) void*client;
@property (nonatomic, readonly) NSArray *nowPlayingClients;

- (void*)activePlayer;
- (void*)activePlayerPath;
- (void*)client;
- (void)dealloc;
- (id)description;
- (id)initWithClient:(void*)arg1;
- (id)nowPlayingClients;
- (id)nowPlayingPlayerClientForPlayerPath:(void*)arg1;
- (void)setActivePlayerPath:(void*)arg1;

@end
