/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRNowPlayingPlayerClientRequests : NSObject {
    int  _notifyRestoreClientStateForLaunch;
    MRPlaybackQueuePlayerPathClient * _playbackQueueClient;
    NSMutableDictionary * _playbackQueueCompletions;
    void * _playerPath;
    NSObject<OS_dispatch_queue> * _serialQueue;
    NSMutableDictionary * _transactionCallbacks;
}

@property (nonatomic, readonly) MRPlaybackQueuePlayerPathClient *playbackQueueClient;
@property (nonatomic, readonly) void*playerPath;

- (void)_registerDefaultCallbacks;
- (void)addPlaybackQueueCompletion:(id /* block */)arg1 forRequest:(void*)arg2;
- (void)addTransactionCallback:(id /* block */)arg1 forName:(unsigned long long)arg2;
- (bool)augmentCommandOptions:(id)arg1 forCommand:(unsigned int)arg2;
- (void)dealloc;
- (id)initWithPlayerPath:(void*)arg1;
- (void)invalidatePlaybackQueue;
- (id)playbackQueueClient;
- (void*)playerPath;
- (void)removePlaybackQueueCompletionForRequest:(void*)arg1;
- (id)transactionCallbacksForName:(unsigned long long)arg1;

@end
