/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRTransactionSource : NSObject {
    unsigned long long  _name;
    NSMutableDictionary * _originSources;
    NSObject<OS_dispatch_queue> * _queue;
}

@property (getter=isActive, nonatomic, readonly) bool active;
@property (nonatomic, readonly) unsigned long long name;

- (void)dealloc;
- (id)initWithName:(unsigned long long)arg1;
- (bool)isActive;
- (unsigned long long)name;
- (void)removePlayer:(void*)arg1;
- (void)sendPackets:(id)arg1 forPlayer:(void*)arg2;

@end
