/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRTransactionSourceOrigin : NSObject {
    bool  _active;
    unsigned long long  _name;
    double  _outOfMemoryWaitDuration;
    MRTransactionPacketizer * _packetizer;
    NSMutableArray * _packets;
    void * _playerPath;
}

@property (getter=isActive, nonatomic, readonly) bool active;

- (void)_begin;
- (void)_cleanUp;
- (void)_processMessage:(id)arg1;
- (void)dealloc;
- (id)initWithName:(unsigned long long)arg1 forPlayer:(void*)arg2;
- (bool)isActive;
- (void)sendPackets:(id)arg1;

@end
