/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface _PFPersistentHistoryModel : NSObject

+ (int)_maxCountOfTombstonesInModel:(id)arg1;
+ (void)createModelsWithTombstoneCount:(int)arg1;
+ (id)newHistorySQLModelWithStoreSQLModel:(id)arg1;
+ (id)newPersistentHistoryModelWithStoreSQLModel:(id)arg1;

@end
