/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface PFCloudKitExporter : NSObject {
    CKDatabase * _database;
    PFCloudKitMirroredRelationshipCache * _generatedCache;
    PFCloudKitStoreMonitor * _monitor;
    NSCloudKitMirroringDelegateOptions * _options;
    NSArray * _writtenAssetURLs;
    CKRecordZone * _zone;
}

- (void)dealloc;
- (void)exportIfNecessaryInTransaction:(id)arg1 onQueue:(id)arg2 completion:(id /* block */)arg3;
- (id)initWithOptions:(id)arg1 store:(id)arg2 zone:(id)arg3 andDatabase:(id)arg4;
- (void)processRecordsToSave:(id)arg1 andRecordIDsToDelete:(id)arg2 inTransaction:(id)arg3 historyTransactionID:(id)arg4 completion:(id /* block */)arg5;
- (bool)shouldExportManagedObject:(id)arg1;

@end
