/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface PFCloudKitSetupAssistant : NSObject {
    NSObject<OS_dispatch_semaphore> * _cloudKitSemaphore;
    CKContainer * _container;
    CKDatabase * _database;
    NSURL * _largeBlobDirectoryURL;
    NSCloudKitMirroringDelegateOptions * _mirroringOptions;
    NSPersistentStoreCoordinator * _observedCoordinator;
    NSPersistentStore * _observedStore;
    CKRecordZone * _zone;
    CKRecordZoneSubscription * _zoneSubscription;
}

@property (nonatomic, readonly) NSObject<OS_dispatch_semaphore> *cloudKitSemaphore;
@property (nonatomic, readonly) CKContainer *container;
@property (nonatomic, readonly) CKDatabase *database;
@property (nonatomic, readonly) NSURL *largeBlobDirectoryURL;
@property (nonatomic, readonly) NSCloudKitMirroringDelegateOptions *mirroringOptions;
@property (nonatomic, readonly) NSPersistentStoreCoordinator *observedCoordinator;
@property (nonatomic, readonly) NSPersistentStore *observedStore;
@property (nonatomic, readonly) CKRecordZone *zone;
@property (nonatomic, readonly) CKRecordZoneSubscription *zoneSubscription;

+ (id)containerWithIdentifier:(id)arg1 andOptions:(id)arg2;

- (void).cxx_destruct;
- (bool)_checkAccountStatus:(id*)arg1;
- (bool)_createSchema:(id*)arg1;
- (bool)_createSchemaIfNecessary:(id*)arg1;
- (bool)_createZoneIfNecessary:(id*)arg1;
- (bool)_initializeAssetStorageURLError:(id*)arg1;
- (bool)_initializeCloudKitForObservedStore:(id*)arg1;
- (void)_setDatabase:(id)arg1;
- (bool)_setupZoneSubscriptionIfNecessary:(id*)arg1;
- (id)cloudKitSemaphore;
- (id)container;
- (id)database;
- (void)dealloc;
- (id)init;
- (id)initWithMirroringOptions:(id)arg1 observedStore:(id)arg2 zone:(id)arg3 zoneSubscription:(id)arg4;
- (id)largeBlobDirectoryURL;
- (id)mirroringOptions;
- (id)observedCoordinator;
- (id)observedStore;
- (id)zone;
- (id)zoneSubscription;

@end
