/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Contacts.framework/Contacts
 */

@interface CNOneBatchFetchEnumerator : NSObject <CNBatchFetchEnumerator> {
    CNQueue * _queue;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) CNQueue *queue;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)initWithBlock:(id /* block */)arg1;
- (id)nextContactsAndMatchInfos:(id*)arg1 error:(id*)arg2;
- (id)queue;

@end
