/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _DKAllChanges : NSObject {
    NSArray * _additionChangeSets;
    NSArray * _deletionChangeSets;
    NSDate * _endDate;
    NSArray * _insertedObjects;
    NSDate * _startDate;
    NSArray * _tombstones;
}

@property (nonatomic, readonly) NSArray *additionChangeSets;
@property (nonatomic, readonly) NSArray *deletionChangeSets;
@property (nonatomic, readonly) NSDate *endDate;
@property (nonatomic, readonly) NSArray *insertedObjects;
@property (nonatomic, readonly) NSDate *startDate;
@property (nonatomic, readonly) NSArray *tombstones;

- (void).cxx_destruct;
- (id)additionChangeSets;
- (id)deletionChangeSets;
- (id)endDate;
- (id)initWithInsertedObjects:(id)arg1 tombstones:(id)arg2 additionChangeSets:(id)arg3 deletionChangeSets:(id)arg4 startDate:(id)arg5 endDate:(id)arg6;
- (id)insertedObjects;
- (id)startDate;
- (id)tombstones;

@end
