/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _DKAttributeValueMO : NSManagedObject

@property (nonatomic, copy) NSData *binaryValue;
@property (nonatomic, retain) NSSet *customMetadata;
@property (nonatomic, copy) NSDate *dateValue;
@property (nonatomic, copy) NSNumber *doubleValue;
@property (nonatomic, copy) NSNumber *integerValue;
@property (nonatomic, copy) NSString *stringValue;
@property (nonatomic, copy) NSString *valueHash;

+ (id)fetchRequest;

@end
