/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _DKAttributeMO : NSManagedObject

@property (nonatomic, retain) NSSet *customMetadata;
@property (nonatomic, copy) NSString *name;

+ (id)fetchRequest;

@end
