/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _DKKnowledgeStorageLogging : NSObject

+ (void)_knowledgeStorageDidInsertEvents:(id)arg1;
+ (void)load;

@end
