/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _DKSyncCoordinatorLogging : NSObject

+ (void)_syncCoordinatorDidAddRemoteEvents:(id)arg1;
+ (void)_syncCoordinatorDidInsertLocalAdditionEvents:(id)arg1;
+ (void)load;
+ (id)portraitStreamNames;

@end
