/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _DKSyncCoordinator : NSObject {
    NSObject<OS_dispatch_queue> * _executionQueue;
    bool  _observersRegistered;
    _DKKnowledgeStorage * _storage;
    NSArray * _streamNamesObserved;
}

@property (nonatomic, readonly) _DKKnowledgeStorage *storage;

+ (id)changeSetForSyncWithInsertedObjects:(id)arg1 startDate:(id)arg2 endDate:(id)arg3;
+ (id)changeSetForSyncWithTombstones:(id)arg1 startDate:(id)arg2 endDate:(id)arg3;

- (void).cxx_destruct;
- (void)_addLastSyncDate:(id)arg1;
- (void)_databaseDidDeleteFromStream:(id)arg1;
- (void)_databaseDidHaveInsertsAndDeletes:(id)arg1;
- (double)_intervalForJobGivenPolicy:(id)arg1 isSingleDevice:(bool)arg2;
- (unsigned long long)_lastChangeCount;
- (id)_lastDaySyncDates;
- (id)_lastSyncDate;
- (void)_performPeriodicJob;
- (bool)_performSyncDownWithPolicy:(id)arg1 additionChangeSets:(id)arg2;
- (bool)_performSyncDownWithPolicy:(id)arg1 allChanges:(id)arg2 error:(id*)arg3;
- (bool)_performSyncDownWithPolicy:(id)arg1 deletionChangeSets:(id)arg2;
- (bool)_performSyncUpWithPolicy:(id)arg1 additionChangeSet:(id)arg2 deletionChangeSet:(id)arg3 error:(id*)arg4;
- (bool)_performSyncUpWithPolicy:(id)arg1 changeSet:(id)arg2;
- (void)_performSyncWithPolicy:(id)arg1 allChanges:(id)arg2 additionChangeSet:(id)arg3 deletionChangeSet:(id)arg4 reply:(id /* block */)arg5;
- (void)_performSyncWithPolicy:(id)arg1 isTriggeredSync:(bool)arg2 reply:(id /* block */)arg3;
- (id)_queryStartDateGivenPolicy:(id)arg1 isTriggeredSync:(bool)arg2;
- (void)_registerDatabaseObservers;
- (void)_registerPeriodicJob;
- (void)_sendNotificationsForAppliedRemoteAdditionChangeSet:(id)arg1;
- (void)_sendNotificationsForAppliedRemoteDeletionChangeSet:(id)arg1 deleted:(unsigned long long)arg2;
- (void)_sendNotificationsForCreatedAdditionChangeSet:(id)arg1;
- (void)_sendNotificationsForCreatedChangeSet:(id)arg1;
- (void)_sendNotificationsForCreatedDeletionChangeSet:(id)arg1;
- (void)_setLastChangeCount:(unsigned long long)arg1;
- (bool)_shouldDeleteZones;
- (void)_unregisterDatabaseObservers;
- (void)_unregisterPeriodicJob;
- (void)dealloc;
- (void)deleteRemoteStateWithReply:(id /* block */)arg1;
- (id)initWithStorage:(id)arg1;
- (void)performSyncWithPolicy:(id)arg1 reply:(id /* block */)arg2;
- (id)storage;
- (void)syncWithReply:(id /* block */)arg1;

@end
