/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContactsUICore.framework/ContactsUICore
 */

@interface CNUICoreRecentsManager : NSObject {
    CRRecentContactsLibrary * _recentsLibrary;
    <CNScheduler> * _workQueue;
}

@property (nonatomic, readonly) CRRecentContactsLibrary *recentsLibrary;
@property (nonatomic, readonly) <CNScheduler> *workQueue;

+ (id)descriptorForRequiredKeys;
+ (id)predicateForSearchingPropertiesOfContact:(id)arg1;
+ (id)propertyDescriptionAndTransformByRecentKind;
+ (id)queryForPropertiesInContact:(id)arg1;
+ (id)supportedRecentsDomains;
+ (id)supportedRecentsKinds;

- (void).cxx_destruct;
- (id)initWithRecentsLibrary:(id)arg1 schedulerProvider:(id)arg2;
- (id)recentsContactsMatchingPropertiesOfContact:(id)arg1;
- (id)recentsLibrary;
- (void)removeRecents:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)workQueue;

@end
