/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIBackButtonContainerView : UIView {
    double  _backButtonLeadingMargin;
    CALayer * _edgeMask;
    UIImage * _edgeMaskImage;
    CALayer * _fillMask;
}

@property (nonatomic) double backButtonLeadingMargin;
@property (nonatomic, retain) UIImage *edgeMaskImage;
@property (nonatomic) bool maskEnabled;

- (void).cxx_destruct;
- (double)backButtonLeadingMargin;
- (id)edgeMaskImage;
- (void)layoutSubviews;
- (bool)maskEnabled;
- (void)setBackButtonLeadingMargin:(double)arg1;
- (void)setEdgeMaskImage:(id)arg1;
- (void)setMaskEnabled:(bool)arg1;

@end
