/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIDropSessionImpl : NSObject <UIDropSession> {
    NSArray * _items;
    <UIDragSession> * _localDragSession;
    unsigned long long  _progressIndicatorStyle;
    _UIInternalDraggingSessionDestination * _sessionDestination;
}

@property (nonatomic, readonly) bool allowsMoveOperation;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSArray *items;
@property (nonatomic, readonly) <UIDragSession> *localDragSession;
@property (getter=_operationMask, nonatomic, readonly) unsigned long long operationMask;
@property (readonly) NSProgress *progress;
@property (nonatomic) unsigned long long progressIndicatorStyle;
@property (getter=isRestrictedToDraggingApplication, nonatomic, readonly) bool restrictedToDraggingApplication;
@property (nonatomic, readonly) _UIInternalDraggingSessionDestination *sessionDestination;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_createItemsOfClass:(Class)arg1 synchronouslyIfPossible:(bool)arg2 completion:(id /* block */)arg3;
- (void)_itemsNeedUpdate:(id)arg1;
- (unsigned long long)_operationMask;
- (bool)allowsMoveOperation;
- (bool)canLoadObjectsOfClass:(Class)arg1;
- (bool)canLoadObjectsOfClasses:(id)arg1;
- (bool)hasItemsConformingToTypeIdentifiers:(id)arg1;
- (id)initWithSessionDestination:(id)arg1;
- (bool)isRestrictedToDraggingApplication;
- (id)items;
- (id)loadObjectsOfClass:(Class)arg1 completion:(id /* block */)arg2;
- (id)localDragSession;
- (struct CGPoint { double x1; double x2; })locationInView:(id)arg1;
- (id)progress;
- (unsigned long long)progressIndicatorStyle;
- (id)session;
- (id)sessionDestination;
- (void)setProgressIndicatorStyle:(unsigned long long)arg1;

@end
