/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIDragManager : NSObject {
    CAContext * _dragImageContext;
    NSArray * _dragSessionDestinations;
    NSArray * _dragSessionSources;
    long long  _pendingSessionRequests;
    NSMutableArray * _pendingSessionRequestsCompletionBlocks;
    UIScreen * _screen;
    _UIDruidSourceWarmUpConnection * _warmUpConnection;
}

@property (nonatomic, readonly) CAContext *dragImageContext;
@property (nonatomic, copy) NSArray *dragSessionDestinations;
@property (nonatomic, copy) NSArray *dragSessionSources;
@property (nonatomic, readonly) UIScreen *screen;

- (void).cxx_destruct;
- (void)_willAddDeactivationReason:(id)arg1;
- (id)beginDragDestinationWithEvent:(id)arg1;
- (id)beginDragWithItems:(id)arg1 touches:(id)arg2 orInitialCentroid:(struct CGPoint { double x1; double x2; })arg3 requiredContextIds:(id)arg4 shouldPerformHitTesting:(bool)arg5 sourceView:(id)arg6 accessibilityEndpoint:(id)arg7;
- (void)deleteSlots:(id)arg1;
- (id)dragImageContext;
- (id)dragSessionDestinations;
- (id)dragSessionSources;
- (bool)hasPendingSessionRequests;
- (id)initWithScreen:(id)arg1;
- (void)performAfterCompletingPendingSessionRequests:(id /* block */)arg1;
- (void)performPendingSessionCompletionBlocksIfPossible;
- (id)screen;
- (void)sessionDestinationDidEnd:(id)arg1;
- (void)sessionSourceDidEnd:(id)arg1;
- (id)sessionSourceWithIdentifier:(unsigned int)arg1;
- (void)setDragSessionDestinations:(id)arg1;
- (void)setDragSessionSources:(id)arg1;
- (unsigned int)uploadImage:(struct CGImage { }*)arg1;
- (void)warmUpDruid;

@end
