/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIInteractiveHighlightEffect : NSObject {
    UIVisualEffectView * _effectView;
    _UIInteractiveHighlightEnvironment * _environment;
    _UIPortalView * _portalView;
    UILayoutGuide * _preferredLayoutGuide;
    UIView * _superview;
    UIView * _view;
}

@property (nonatomic) UIVisualEffectView *effectView;
@property (nonatomic, retain) _UIInteractiveHighlightEnvironment *environment;
@property (nonatomic) _UIPortalView *portalView;
@property (nonatomic) UILayoutGuide *preferredLayoutGuide;
@property (nonatomic) UIView *superview;
@property (nonatomic) UIView *view;

- (void).cxx_destruct;
- (void)applyBackgroundEffectWithMagnitude:(double)arg1 interactive:(bool)arg2 completion:(id /* block */)arg3;
- (void)dealloc;
- (id)effectView;
- (id)environment;
- (void)finalizeEffect;
- (id)portalView;
- (id)preferredLayoutGuide;
- (void)setEffectView:(id)arg1;
- (void)setEnvironment:(id)arg1;
- (void)setPortalView:(id)arg1;
- (void)setPreferredLayoutGuide:(id)arg1;
- (void)setSuperview:(id)arg1;
- (void)setView:(id)arg1;
- (id)superview;
- (id)view;

@end
