/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UILayerHostView : UIView

@property (nonatomic) unsigned int contextID;
@property (nonatomic) bool inheritsSecurity;
@property (nonatomic, readonly, retain) CALayerHost *layerHost;

+ (Class)layerClass;

- (unsigned int)contextID;
- (void)dealloc;
- (bool)inheritsSecurity;
- (id)layerHost;
- (void)setContextID:(unsigned int)arg1;
- (void)setInheritsSecurity:(bool)arg1;

@end
