/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UINavigationBarTitleView : UIView <_UINavigationBarAugmentedTitleView> {
    <_UINavigationBarTitleViewDataSource> * _dataSource;
    double  _height;
    NSLayoutConstraint * _heightConstraint;
    bool  _hideBackButton;
    bool  _hideLeadingBarButtons;
    bool  _hideStandardTitle;
    bool  _hideTrailingBarButtons;
    UINavigationItem * _navigationItem;
    long long  _titleLocation;
    bool  _underlayBarContent;
}

@property (getter=_dataSource, setter=_setDataSource:, nonatomic) <_UINavigationBarTitleViewDataSource> *_dataSource;
@property (nonatomic, readonly, copy) NSArray *contentOverlayRects;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) double height;
@property (nonatomic) bool hideBackButton;
@property (nonatomic) bool hideLeadingBarButtons;
@property (nonatomic) bool hideStandardTitle;
@property (nonatomic) bool hideTrailingBarButtons;
@property (nonatomic) UINavigationItem *navigationItem;
@property (readonly) Class superclass;
@property (nonatomic) long long titleLocation;
@property (nonatomic) bool underlayBarContent;

- (void).cxx_destruct;
- (id)_dataSource;
- (void)_setDataSource:(id)arg1;
- (id)contentOverlayRects;
- (double)height;
- (bool)hideBackButton;
- (bool)hideLeadingBarButtons;
- (bool)hideStandardTitle;
- (bool)hideTrailingBarButtons;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)navigationItem;
- (void)performTransition:(long long)arg1 willBeDisplayed:(bool)arg2;
- (void)preferredContentSizeDidChange;
- (long long)preferredContentSizeForSize:(long long)arg1;
- (void)setHeight:(double)arg1;
- (void)setHideBackButton:(bool)arg1;
- (void)setHideLeadingBarButtons:(bool)arg1;
- (void)setHideStandardTitle:(bool)arg1;
- (void)setHideTrailingBarButtons:(bool)arg1;
- (void)setNavigationItem:(id)arg1;
- (void)setTitleLocation:(long long)arg1;
- (void)setTranslatesAutoresizingMaskIntoConstraints:(bool)arg1;
- (void)setUnderlayBarContent:(bool)arg1;
- (long long)titleLocation;
- (void)transitionCompleted:(long long)arg1 willBeDisplayed:(bool)arg2;
- (void)transitionWillBegin:(long long)arg1 willBeDisplayed:(bool)arg2;
- (bool)underlayBarContent;

@end
