/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UISpringLoadedScaleEffect : NSObject <UISpringLoadedInteractionEffect> {
    _UIPortalView * _portalView;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) _UIPortalView *portalView;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_animateToDefaultState;
- (void)_emphasizeSpringLoadingAnimation;
- (void)_enableSpringLoadingAnimationWithView:(id)arg1;
- (id)effectContainer;
- (void)interaction:(id)arg1 didChangeWithContext:(id)arg2;
- (id)portalView;
- (void)setPortalView:(id)arg1;

@end
