/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UITableViewSubviewManager : NSObject {
    NSMapTable * _cellsReadyForReuse;
    NSCountedSet * _dropAnimationCells;
    UITableViewCell * _reorderingCell;
    NSCountedSet * _reusePreventedCells;
    UITableView<_UITableViewSubviewManagerDelegate> * _tableView;
}

@property (nonatomic, retain) NSMapTable *cellsReadyForReuse;
@property (nonatomic, retain) NSCountedSet *dropAnimationCells;
@property (nonatomic, retain) UITableViewCell *reorderingCell;
@property (nonatomic, retain) NSCountedSet *reusePreventedCells;
@property (nonatomic) UITableView<_UITableViewSubviewManagerDelegate> *tableView;

- (void).cxx_destruct;
- (void)beginDropAnimationForCell:(id)arg1;
- (void)cellReadyForReuse:(id)arg1 withIndexPath:(id)arg2 didEndDisplaying:(bool)arg3;
- (bool)cellShouldRemainHiddenForDropAnimation:(id)arg1;
- (id)cellsReadyForReuse;
- (id)dropAnimationCells;
- (void)endDropAnimationForCell:(id)arg1;
- (id)initWithTableView:(id)arg1;
- (void)preventReuseOfCell:(id)arg1;
- (id)reorderingCell;
- (void)resumeReuseOfCell:(id)arg1;
- (id)reusePreventedCells;
- (void)setCellsReadyForReuse:(id)arg1;
- (void)setDropAnimationCells:(id)arg1;
- (void)setReorderingCell:(id)arg1;
- (void)setReusePreventedCells:(id)arg1;
- (void)setTableView:(id)arg1;
- (bool)shouldDeferReuseOfCell:(id)arg1;
- (id)tableView;

@end
