/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UITAMICAdaptorView : UIView <_UIGeometryChangeObserver> {
    NSLayoutConstraint * _height;
    bool  _inLayout;
    struct CGSize { 
        double width; 
        double height; 
    }  _layoutSize;
    UILayoutGuide * _sizingLayoutGuide;
    UIView * _view;
    NSLayoutConstraint * _width;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UILayoutGuide *sizingLayoutGuide;
@property (readonly) Class superclass;

+ (bool)shouldWrapView:(id)arg1;

- (void).cxx_destruct;
- (void)_didMoveFromWindow:(id)arg1 toWindow:(id)arg2;
- (void)_geometryChanges:(id)arg1 forAncestor:(id)arg2;
- (id)initWithView:(id)arg1;
- (void)layoutSubviews;
- (void)setSizingLayoutGuide:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (id)sizingLayoutGuide;
- (void)updateForAvailableSize;

@end
