/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UITableViewDropAnimation : NSObject {
    UIDragItem * _dragItem;
}

@property (nonatomic, retain) UIDragItem *dragItem;

- (void).cxx_destruct;
- (id)dragItem;
- (id)initWithDragItem:(id)arg1;
- (void)setDragItem:(id)arg1;

@end
