/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIAccessibilityHUDItem : NSObject <NSCopying> {
    UIImage * _image;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _imageInsets;
    bool  _scaleImage;
    NSString * _title;
}

@property (nonatomic, retain) UIImage *image;
@property (nonatomic) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } imageInsets;
@property (nonatomic) bool scaleImage;
@property (nonatomic, copy) NSString *title;

+ (id)HUDItemForBarButtonItem:(id)arg1;
+ (id)HUDItemForTabBarItem:(id)arg1;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned long long)hash;
- (id)image;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })imageInsets;
- (id)initWithTitle:(id)arg1 image:(id)arg2 imageInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg3;
- (id)initWithTitle:(id)arg1 image:(id)arg2 imageInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg3 scaleImage:(bool)arg4;
- (bool)isEqual:(id)arg1;
- (bool)scaleImage;
- (void)setImage:(id)arg1;
- (void)setImageInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setScaleImage:(bool)arg1;
- (void)setTitle:(id)arg1;
- (id)title;

@end
