/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIAccessibilityHUDGestureManager : NSObject <UIGestureRecognizerDelegatePrivate> {
    UILongPressGestureRecognizer * _recognizer;
    NSMutableArray * _subscribedConcurrentGestureRecognizers;
    UIView<UIAccessibilityHUDGestureHosting> * _view;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_clearButtonItemGestureSubscriptions;
- (void)_concurrentGestureRecognizerFired:(id)arg1;
- (void)_contentSizeCategoryChanged:(id)arg1;
- (bool)_gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)_gestureRecognizerChanged:(id)arg1;
- (id)_subscribedConcurrentGestureRecognizers;
- (void)dealloc;
- (id)initWithView:(id)arg1;

@end
