/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBRenderFactory_iPhoneTruffleReachable : UIKBRenderFactory_Composite

- (Class)_baseFactoryClass;
- (Class)_overlayFactoryClass;
- (id)_overlayMethodSelectors;

@end
