/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBRenderFactory_Composite : UIKBRenderFactory {
    UIKBRenderFactory * _baseFactory;
    UIKBRenderFactory * _overlayFactory;
}

- (Class)_baseFactoryClass;
- (Class)_overlayFactoryClass;
- (id)_overlayMethodSelectors;
- (void)forwardInvocation:(id)arg1;
- (id)initWithRenderingContext:(id)arg1 skipLayoutSegments:(bool)arg2;
- (id)methodSignatureForSelector:(SEL)arg1;

@end
