/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBRenderFactory10Key_LandscapeTruffle : UIKBRenderFactory10Key_Landscape

- (double)centerColumnWidthFactor;
- (double)controlColumnWidthFactor;

@end
