/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKeyboardHiddenViewController : UIViewController <UIPopoverPresentationControllerDelegate, UIViewControllerTransitioningDelegate, _SFAppAutoFillPasswordViewControllerDelegate> {
    bool  _shouldPresentRemoteAsPopover;
    UIView * _sourceView;
    bool  presentedAutofill;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool shouldPresentRemoteAsPopover;
@property (nonatomic) UIView *sourceView;
@property (readonly) Class superclass;

- (void)_localAuthenticationUIDismissed;
- (void)_localAuthenticationUIPresented;
- (void)_willChangeToFirstResponder:(id)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)passwordViewControllerDidFinish:(id)arg1;
- (void)prepareForPopoverPresentation:(id)arg1;
- (void)presentAutofillVC;
- (id)presentationControllerForPresentedViewController:(id)arg1 presentingViewController:(id)arg2 sourceViewController:(id)arg3;
- (void)setShouldPresentRemoteAsPopover:(bool)arg1;
- (void)setSourceView:(id)arg1;
- (bool)shouldPresentRemoteAsPopover;
- (id)sourceView;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;

@end
