/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarLocationItemView : UIStatusBarItemView {
    int  _iconType;
}

// Image: /Developer/usr/lib/libMainThreadChecker.dylib

- (id)contentsImage;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;

@end
