/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarPersonNameItemView : UIStatusBarItemView {
    double  _letterSpacing;
    double  _maxWidth;
    NSString * _personNameString;
}

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (bool)_updateWithPersonName:(id)arg1 maxWidth:(double)arg2;

// Image: /Developer/usr/lib/libMainThreadChecker.dylib

- (void).cxx_destruct;
- (double)addContentOverlap:(double)arg1;
- (id)contentsImage;
- (long long)legibilityStyle;
- (double)resetContentOverlap;
- (double)standardPadding;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;

@end
