/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarBatteryPercentItemView : UIStatusBarItemView {
    NSString * _percentString;
}

// Image: /Developer/usr/lib/libMainThreadChecker.dylib

- (void).cxx_destruct;
- (bool)animatesDataChange;
- (id)contentsImage;
- (double)extraRightPadding;
- (long long)textAlignment;
- (long long)textStyle;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;

@end
