/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarReturnToCallItemView : UIStatusBarAppIconItemView {
    UILabel * _textLabel;
}

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (id)_appBundleIdentifier;

// Image: /Developer/usr/lib/libMainThreadChecker.dylib

- (void).cxx_destruct;
- (long long)buttonType;
- (void)layoutSubviews;
- (double)neededSizeForImageSet:(id)arg1;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;

@end
