/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarActivityItemView : UIStatusBarItemView {
    UIActivityIndicatorView * _activityIndicator;
    bool  _slowActivity;
    bool  _syncActivity;
}

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (long long)_activityIndicatorStyle;
- (void)_startAnimating;
- (void)_stopAnimating;

// Image: /Developer/usr/lib/libMainThreadChecker.dylib

- (void).cxx_destruct;
- (void)setVisible:(bool)arg1;
- (double)shadowPadding;
- (double)updateContentsAndWidth;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;

@end
