/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UISwipeActionsConfiguration : NSObject {
    NSArray * _actions;
    bool  _performsFirstActionWithFullSwipe;
}

@property (nonatomic, readonly, copy) NSArray *actions;
@property (nonatomic) bool performsFirstActionWithFullSwipe;

+ (id)configurationWithActions:(id)arg1;

- (void).cxx_destruct;
- (id)actions;
- (id)init;
- (bool)performsFirstActionWithFullSwipe;
- (void)setPerformsFirstActionWithFullSwipe:(bool)arg1;

@end
