/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UITableViewLabel : UILabel {
    double  _firstParagraphFirstLineHeadIndent;
    bool  _numberOfLinesSet;
    NSAttributedString * _shadowAttributedText;
    UITableViewCell * _tableCell;
}

@property (nonatomic) UITableViewCell *tableCell;

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (id)_disabledFontColor;
- (void)_setFirstParagraphFirstLineHeadIndent:(double)arg1;
- (void)_setNumberOfLinesForAXLayoutIfNecessary;

// Image: /Developer/usr/lib/libMainThreadChecker.dylib

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setAttributedText:(id)arg1;
- (void)setNumberOfLines:(long long)arg1;
- (void)setTableCell:(id)arg1;
- (void)setText:(id)arg1;
- (id)tableCell;
- (void)traitCollectionDidChange:(id)arg1;

@end
