/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UITextFieldRoundedRectBackgroundView : UITextFieldBackgroundView {
    UIImageView * _center;
    UIImageView * _leftCap;
    UIImageView * _progressFill;
    UIImageView * _rightCap;
}

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (void)_updateImages;

// Image: /Developer/usr/lib/libMainThreadChecker.dylib

- (void).cxx_destruct;
- (void)dealloc;
- (void)layoutSubviews;

@end
