/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UITextGestureClusterLoupeWithVariableDelay : UITextGestureClusterLoupe

+ (Class)loupeGestureType;

- (void)adjustLoupeGesture;
- (id)initWithView:(id)arg1;

@end
