/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface _GEOExperimentServiceRequestConfig : GEOServiceRequestDefaultConfig

+ (id)standardConfig;

- (unsigned long long)urlType;

@end
