/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface _GEOServiceRequesterOp : NSObject <GEOPBSessionRequesterDelegate> {
    NSDictionary * _additionalHTTPHeaders;
    NSArray * _additionalURLQueryItems;
    GEOApplicationAuditToken * _auditToken;
    id /* block */  _completionHandler;
    NSString * _debugRequestName;
    int  _experimentDispatcherRequestType;
    long long  _experimentType;
    PBRequest * _request;
    NSNumber * _serviceTypeNumber;
    bool  _shouldThrottleRequests;
    NSString * _throttleKey;
    double  _timeout;
    GEOMapServiceTraits * _traits;
    unsigned long long  _urlType;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_cleanup;
- (void)cancel;
- (void)dealloc;
- (id)initWithRequest:(id)arg1 auditToken:(id)arg2 urlType:(unsigned long long)arg3 additionalURLQueryItems:(id)arg4 additionalHTTPHeaders:(id)arg5 debugRequestName:(id)arg6 serviceType:(id)arg7 experimentType:(long long)arg8 experimentDispatcherRequestType:(int)arg9 timeout:(double)arg10 shouldThrottleRequests:(bool)arg11 throttleKey:(id)arg12 traits:(id)arg13;
- (void)startWithCompletionHandler:(id /* block */)arg1;

@end
