/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface _GEOPBSessionRequesterOp : _GEOServiceRequesterOp {
    bool  _cancelled;
    GEORequester * _requester;
}

- (void).cxx_destruct;
- (void)_cleanup;
- (void)cancel;
- (void)requester:(id)arg1 didFailWithError:(id)arg2;
- (void)requesterDidCancel:(id)arg1;
- (void)requesterDidFinish:(id)arg1;
- (void)startWithCompletionHandler:(id /* block */)arg1;

@end
