/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface _GEOPhoneNumbersTicket : GEOAbstractMapServiceTicket {
    bool  _allowCellularDataForLookup;
    NSArray * _phoneNumbers;
}

- (void).cxx_destruct;
- (id)description;
- (id)initWithPhoneNumbers:(id)arg1 allowCellularDataForLookup:(bool)arg2 traits:(id)arg3;
- (void)submitWithHandler:(id /* block */)arg1 timeout:(long long)arg2 networkActivity:(id /* block */)arg3;

@end
