/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface _GEOIdentifiersTicket : GEOAbstractMapServiceTicket {
    NSString * _contentProvider;
    NSArray * _identifiers;
    bool  _includeETA;
    unsigned long long  _options;
    int  _resultProviderID;
}

- (void).cxx_destruct;
- (id)description;
- (id)initWithIdentifiers:(id)arg1 resultProviderID:(int)arg2 contentProvider:(id)arg3 includeETA:(bool)arg4 traits:(id)arg5 options:(unsigned long long)arg6;
- (id)initWithMUIDs:(id)arg1 resultProviderID:(int)arg2 contentProvider:(id)arg3 includeETA:(bool)arg4 traits:(id)arg5 options:(unsigned long long)arg6;
- (void)submitWithHandler:(id /* block */)arg1 timeout:(long long)arg2 networkActivity:(id /* block */)arg3;

@end
