/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface _GEOPlaceRequestTicket : GEOAbstractMapServiceTicket {
    <GEOMapItem> * _mapItemToRefine;
    GEOPDPlaceRequest * _request;
    GEOPDPlaceResponse * _response;
}

- (void).cxx_destruct;
- (void)_processRequest:(id)arg1 withHandler:(id /* block */)arg2 refinedHandler:(id /* block */)arg3 networkActivity:(id /* block */)arg4;
- (void)applyToCorrectedSearch:(id)arg1;
- (void)applyToPlaceInfo:(id)arg1;
- (void)cancel;
- (id)description;
- (id)initWithRequest:(id)arg1 traits:(id)arg2;
- (id)initWithRequest:(id)arg1 traits:(id)arg2 mapItemToRefine:(id)arg3;
- (id)resultSectionHeader;
- (void)submitWithHandler:(id /* block */)arg1 timeout:(long long)arg2 networkActivity:(id /* block */)arg3;
- (void)submitWithRefinedHandler:(id /* block */)arg1 timeout:(long long)arg2 networkActivity:(id /* block */)arg3;

@end
