/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface _GEOLocationShiftRequestConfig : GEOServiceRequestDefaultConfig

+ (id)standardConfig;

- (id)serviceTypeNumber;
- (unsigned long long)urlType;

@end
