/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOAlertNonRecommendedRouteText : PBCodable <NSCopying> {
    GEOFormattedString * _responseAlertPrimary;
    GEOFormattedString * _responseAlertSecondary;
}

@property (nonatomic, readonly) bool hasResponseAlertPrimary;
@property (nonatomic, readonly) bool hasResponseAlertSecondary;
@property (nonatomic, retain) GEOFormattedString *responseAlertPrimary;
@property (nonatomic, retain) GEOFormattedString *responseAlertSecondary;

- (void).cxx_destruct;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasResponseAlertPrimary;
- (bool)hasResponseAlertSecondary;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (id)responseAlertPrimary;
- (id)responseAlertSecondary;
- (void)setResponseAlertPrimary:(id)arg1;
- (void)setResponseAlertSecondary:(id)arg1;
- (void)writeTo:(id)arg1;

@end
