/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOApplicationAuditToken : NSObject <NSSecureCoding> {
    NSString * _bundleId;
    NSData * _tokenData;
}

@property (nonatomic, readonly) NSString *bundleId;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)backingTokenData;
- (id)bundleId;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithApplicationBundleId:(id)arg1;
- (id)initWithAuditTokenData:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithXPCConnection:(id)arg1;
- (bool)isEqual:(id)arg1;

@end
