/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEODataURLSessionTask : NSObject <GEODataSessionTask, GEOStateCapturing> {
    NSURLSessionDataTask * _backingTask;
    bool  _backingTaskNeedsResume;
    NSData * _cachedData;
    <GEODataSessionTaskDelegate> * _delegate;
    NSObject<OS_dispatch_queue> * _delegateQueue;
    double  _endTime;
    NSError * _error;
    bool  _finished;
    NSMutableData * _receivedData;
    GEODataRequest * _request;
    int  _requestKind;
    NSObject<OS_dispatch_queue> * _sessionIsolation;
    double  _startTime;
    unsigned long long  _stateCaptureHandle;
    unsigned int  _taskIdentifier;
    NSURLSessionTaskMetrics * _urlTaskMetrics;
}

@property (nonatomic, readonly) long long HTTPStatusCode;
@property (nonatomic, readonly) NSURLSessionDataTask *backingTask;
@property (nonatomic, copy) NSData *cachedData;
@property (nonatomic, readonly) GEOClientMetrics *clientMetrics;
@property (nonatomic, readonly) unsigned long long contentLength;
@property (nonatomic, readonly) NSString *contentLengthString;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, readonly) <GEODataSessionTaskDelegate> *delegate;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *delegateQueue;
@property (readonly, copy) NSString *description;
@property (readonly) double elapsedTime;
@property (nonatomic, readonly) NSString *entityTag;
@property (nonatomic, readonly) NSError *error;
@property (nonatomic, readonly) bool failedDueToCancel;
@property (readonly) bool failedDueToCancel;
@property (nonatomic, readonly) bool finished;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) unsigned long long incomingPayloadSize;
@property (nonatomic, readonly) NSURL *originalRequestURL;
@property (nonatomic, readonly) NSURLRequest *originalURLRequest;
@property (nonatomic, readonly) unsigned long long outgoingPayloadSize;
@property (nonatomic, readonly) bool protocolBufferHasPreamble;
@property (nonatomic, readonly) NSData *receivedData;
@property (nonatomic, readonly) NSString *remoteAddressAndPort;
@property (nonatomic, readonly) GEODataRequest *request;
@property (nonatomic, readonly) int requestKind;
@property (nonatomic, readonly) NSHTTPURLResponse *response;
@property (nonatomic, readonly) double startTime;
@property (readonly) Class superclass;
@property (nonatomic, readonly) unsigned int taskIdentifier;
@property (nonatomic, readonly) NSURLSessionTaskMetrics *urlTaskMetrics;

- (void).cxx_destruct;
- (long long)HTTPStatusCode;
- (void)_prepareForRestart;
- (id)backingTask;
- (id)cachedData;
- (void)cancel;
- (id)captureStateWithHints:(struct os_state_hints_s { unsigned int x1; char *x2; unsigned int x3; unsigned int x4; }*)arg1;
- (id)clientMetrics;
- (unsigned long long)contentLength;
- (id)contentLengthString;
- (id)createURLSessionTaskWithSession:(id)arg1 request:(id)arg2;
- (void)dataSession:(id)arg1 taskDidCompleteWithError:(id)arg2;
- (void)dealloc;
- (id)delegate;
- (id)delegateQueue;
- (id)description;
- (void)didCollectMetrics:(id)arg1;
- (void)didReceiveData:(id)arg1;
- (void)didReceiveResponse:(id)arg1 completionHandler:(id /* block */)arg2;
- (bool)didValidateEntityTagForData:(id*)arg1 entityTag:(id*)arg2;
- (double)elapsedTime;
- (id)entityTag;
- (id)error;
- (bool)failedDueToCancel;
- (bool)finished;
- (unsigned long long)incomingPayloadSize;
- (id)init;
- (id)initWithSession:(id)arg1 delegate:(id)arg2 delegateQueue:(id)arg3 requestKind:(int)arg4;
- (id)originalRequestURL;
- (id)originalURLRequest;
- (unsigned long long)outgoingPayloadSize;
- (bool)protocolBufferHasPreamble;
- (id)receivedData;
- (id)remoteAddressAndPort;
- (id)request;
- (int)requestKind;
- (id)response;
- (void)setCachedData:(id)arg1;
- (void)start;
- (double)startTime;
- (unsigned int)taskIdentifier;
- (id)urlTaskMetrics;
- (bool)validateContentLengthWithError:(id*)arg1;
- (bool)validateNonEmptyResponseWithError:(id*)arg1;
- (bool)validateTileResponseWithError:(id*)arg1;

@end
