/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEODataXPCSessionTaskQueue : NSObject {
    <GEODataXPCConnectionManager> * _connectionManager;
    NSMutableIndexSet * _inflightQueues;
    NSObject<OS_dispatch_queue> * _isolation;
    NSMutableDictionary * _pendingTasks;
}

@property (nonatomic, readonly) <GEODataXPCConnectionManager> *connectionManager;
@property (nonatomic, readonly) NSMutableIndexSet *inflightQueues;
@property (nonatomic, readonly) NSMutableDictionary *pendingTasks;

- (void).cxx_destruct;
- (id)connectionManager;
- (id)description;
- (void)enqueueTask:(id)arg1;
- (id)inflightQueues;
- (id)init;
- (id)initWithIsolationQueue:(id)arg1 connectionManager:(id)arg2;
- (id)pendingTasks;
- (bool)removeQueuedTask:(id)arg1;
- (void)sendNextTaskForQueue:(unsigned int)arg1;
- (void)sendTask:(id)arg1;
- (void)sendTaskImmediately:(id)arg1;

@end
