/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOGeocodeRequester : GEOServiceRequester

+ (id)sharedGeocodeRequester;

- (void)batchReverseGeocode:(id)arg1 success:(id /* block */)arg2 networkActivity:(id /* block */)arg3 error:(id /* block */)arg4;
- (void)cancelBatchReverseGeocode:(id)arg1;

@end
