/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOGuidanceEventFeedback : PBCodable <NSCopying> {
    int  _guidanceEventIndex;
    struct { 
        unsigned int guidanceEventIndex : 1; 
        unsigned int timeToManeuver : 1; 
    }  _has;
    GEOSignGuidanceFeedback * _signGuidanceFeedback;
    GEOSpokenGuidanceFeedback * _spokenGuidanceFeedback;
    float  _timeToManeuver;
}

@property (nonatomic) int guidanceEventIndex;
@property (nonatomic) bool hasGuidanceEventIndex;
@property (nonatomic, readonly) bool hasSignGuidanceFeedback;
@property (nonatomic, readonly) bool hasSpokenGuidanceFeedback;
@property (nonatomic) bool hasTimeToManeuver;
@property (nonatomic, retain) GEOSignGuidanceFeedback *signGuidanceFeedback;
@property (nonatomic, retain) GEOSpokenGuidanceFeedback *spokenGuidanceFeedback;
@property (nonatomic) float timeToManeuver;

- (void).cxx_destruct;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (int)guidanceEventIndex;
- (bool)hasGuidanceEventIndex;
- (bool)hasSignGuidanceFeedback;
- (bool)hasSpokenGuidanceFeedback;
- (bool)hasTimeToManeuver;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setGuidanceEventIndex:(int)arg1;
- (void)setHasGuidanceEventIndex:(bool)arg1;
- (void)setHasTimeToManeuver:(bool)arg1;
- (void)setSignGuidanceFeedback:(id)arg1;
- (void)setSpokenGuidanceFeedback:(id)arg1;
- (void)setTimeToManeuver:(float)arg1;
- (id)signGuidanceFeedback;
- (id)spokenGuidanceFeedback;
- (float)timeToManeuver;
- (void)writeTo:(id)arg1;

@end
