/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOLocationCollectionReporter : NSObject

+ (void)reportBatchLocationCollection:(id)arg1;
+ (void)reportRealtimeLocationCollection:(id)arg1;

@end
