/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOMapItemParentVenue : NSObject {
    GEOVenueLabel * _buildingLabel;
    <GEOVenueIdentifier> * _venueIdentifier;
    GEOVenueLabel * _venueLabel;
}

@property (nonatomic, readonly) GEOVenueLabel *buildingLabel;
@property (nonatomic, readonly) <GEOVenueIdentifier> *venueIdentifier;
@property (nonatomic, readonly) GEOVenueLabel *venueLabel;

- (void).cxx_destruct;
- (id)buildingLabel;
- (id)initWithIdentifier:(id)arg1 venueLabel:(id)arg2 buildingLabel:(id)arg3;
- (id)venueIdentifier;
- (id)venueLabel;

@end
