/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOMapItemVenueInfo : NSObject <GEOMapItemVenueInfo> {
    NSArray * _buildings;
    <GEOMapItemVenueContents> * _contents;
    GEOMapItemParentVenue * _parent;
    int  _venueBrowseType;
    int  _venueFeatureType;
    <GEOVenueIdentifier> * _venueIdentifier;
}

@property (nonatomic, readonly) NSArray *buildings;
@property (nonatomic, readonly) <GEOMapItemVenueContents> *contents;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) GEOMapItemParentVenue *parent;
@property (readonly) Class superclass;
@property (nonatomic, readonly) int venueBrowseType;
@property (nonatomic, readonly) int venueFeatureType;
@property (nonatomic, readonly) <GEOVenueIdentifier> *venueIdentifier;

+ (id)fakeVenueInfoForPlace:(id)arg1;

- (void).cxx_destruct;
- (id)buildings;
- (id)contents;
- (id)initWithIdentifier:(id)arg1 featureType:(int)arg2 browseType:(int)arg3 buildings:(id)arg4 parent:(id)arg5 contents:(id)arg6;
- (id)initWithVenueInfo:(id)arg1;
- (id)parent;
- (int)venueBrowseType;
- (int)venueFeatureType;
- (id)venueIdentifier;

@end
