/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOPDVenueIdentifier : PBCodable <NSCopying> {
    unsigned long long  _buildingId;
    unsigned long long  _directoryGroupingId;
    unsigned long long  _fixtureId;
    struct { 
        unsigned int buildingId : 1; 
        unsigned int directoryGroupingId : 1; 
        unsigned int fixtureId : 1; 
        unsigned int levelId : 1; 
        unsigned int unitId : 1; 
        unsigned int venueId : 1; 
        unsigned int levelOrdinal : 1; 
    }  _has;
    unsigned long long  _levelId;
    int  _levelOrdinal;
    struct { 
        unsigned long long *list; 
        unsigned long long count; 
        unsigned long long size; 
    }  _sectionIds;
    unsigned long long  _unitId;
    PBUnknownFields * _unknownFields;
    unsigned long long  _venueId;
}

@property (nonatomic) unsigned long long buildingId;
@property (nonatomic) unsigned long long directoryGroupingId;
@property (nonatomic) unsigned long long fixtureId;
@property (nonatomic) bool hasBuildingId;
@property (nonatomic) bool hasDirectoryGroupingId;
@property (nonatomic) bool hasFixtureId;
@property (nonatomic) bool hasLevelId;
@property (nonatomic) bool hasLevelOrdinal;
@property (nonatomic) bool hasUnitId;
@property (nonatomic) bool hasVenueId;
@property (nonatomic) unsigned long long levelId;
@property (nonatomic) int levelOrdinal;
@property (nonatomic, readonly) unsigned long long*sectionIds;
@property (nonatomic, readonly) unsigned long long sectionIdsCount;
@property (nonatomic) unsigned long long unitId;
@property (nonatomic, readonly) PBUnknownFields *unknownFields;
@property (nonatomic) unsigned long long venueId;

+ (id)venueIdentifiersForIdentifier:(id)arg1;

- (void).cxx_destruct;
- (void)addSectionId:(unsigned long long)arg1;
- (unsigned long long)buildingId;
- (void)clearSectionIds;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)directoryGroupingId;
- (unsigned long long)fixtureId;
- (bool)hasBuildingId;
- (bool)hasDirectoryGroupingId;
- (bool)hasFixtureId;
- (bool)hasLevelId;
- (bool)hasLevelOrdinal;
- (bool)hasUnitId;
- (bool)hasVenueId;
- (unsigned long long)hash;
- (id)initWithIdentifier:(id)arg1;
- (id)initWithVenueID:(unsigned long long)arg1;
- (id)initWithVenueID:(unsigned long long)arg1 componentIdentifier:(id)arg2;
- (bool)isEqual:(id)arg1;
- (unsigned long long)levelId;
- (int)levelOrdinal;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (unsigned long long)sectionIdAtIndex:(unsigned long long)arg1;
- (unsigned long long*)sectionIds;
- (unsigned long long)sectionIdsCount;
- (void)setBuildingId:(unsigned long long)arg1;
- (void)setDirectoryGroupingId:(unsigned long long)arg1;
- (void)setFixtureId:(unsigned long long)arg1;
- (void)setHasBuildingId:(bool)arg1;
- (void)setHasDirectoryGroupingId:(bool)arg1;
- (void)setHasFixtureId:(bool)arg1;
- (void)setHasLevelId:(bool)arg1;
- (void)setHasLevelOrdinal:(bool)arg1;
- (void)setHasUnitId:(bool)arg1;
- (void)setHasVenueId:(bool)arg1;
- (void)setLevelId:(unsigned long long)arg1;
- (void)setLevelOrdinal:(int)arg1;
- (void)setSectionIds:(unsigned long long*)arg1 count:(unsigned long long)arg2;
- (void)setUnitId:(unsigned long long)arg1;
- (void)setVenueId:(unsigned long long)arg1;
- (unsigned long long)unitId;
- (id)unknownFields;
- (unsigned long long)venueId;
- (void)writeTo:(id)arg1;

@end
