/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOSearchAttributionManifestManager : NSObject {
    <GEOSearchAttributionServerProxy> * _serverProxy;
}

@property (nonatomic, readonly) <GEOSearchAttributionServerProxy> *serverProxy;

+ (void)setUseLocalProxy:(bool)arg1;
+ (id)sharedManager;
+ (void)useLocalProxy;
+ (void)useProxy:(Class)arg1;
+ (void)useRemoteProxy;

- (void).cxx_destruct;
- (id)init;
- (void)loadAttributionInfoForIdentifier:(id)arg1 version:(unsigned int)arg2 completionHandler:(id /* block */)arg3 errorHandler:(id /* block */)arg4;
- (id)serverProxy;

@end
