/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOStepFeedback : PBCodable <NSCopying> {
    bool  _completedStep;
    double  _completionTimeStamp;
    NSMutableArray * _guidanceFeedbacks;
    struct { 
        unsigned int completionTimeStamp : 1; 
        unsigned int routeIndex : 1; 
        unsigned int stepID : 1; 
        unsigned int completedStep : 1; 
    }  _has;
    NSMutableArray * _instructionErrors;
    NSData * _routeID;
    unsigned int  _routeIndex;
    unsigned int  _stepID;
}

@property (nonatomic) bool completedStep;
@property (nonatomic) double completionTimeStamp;
@property (nonatomic, retain) NSMutableArray *guidanceFeedbacks;
@property (nonatomic) bool hasCompletedStep;
@property (nonatomic) bool hasCompletionTimeStamp;
@property (nonatomic, readonly) bool hasRouteID;
@property (nonatomic) bool hasRouteIndex;
@property (nonatomic) bool hasStepID;
@property (nonatomic, retain) NSMutableArray *instructionErrors;
@property (nonatomic, retain) NSData *routeID;
@property (nonatomic) unsigned int routeIndex;
@property (nonatomic) unsigned int stepID;

+ (Class)guidanceFeedbackType;
+ (Class)instructionErrorType;

- (void).cxx_destruct;
- (void)addGuidanceFeedback:(id)arg1;
- (void)addInstructionError:(id)arg1;
- (void)clearGuidanceFeedbacks;
- (void)clearInstructionErrors;
- (bool)completedStep;
- (double)completionTimeStamp;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (id)guidanceFeedbackAtIndex:(unsigned long long)arg1;
- (id)guidanceFeedbacks;
- (unsigned long long)guidanceFeedbacksCount;
- (bool)hasCompletedStep;
- (bool)hasCompletionTimeStamp;
- (bool)hasRouteID;
- (bool)hasRouteIndex;
- (bool)hasStepID;
- (unsigned long long)hash;
- (id)instructionErrorAtIndex:(unsigned long long)arg1;
- (id)instructionErrors;
- (unsigned long long)instructionErrorsCount;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (id)routeID;
- (unsigned int)routeIndex;
- (void)setCompletedStep:(bool)arg1;
- (void)setCompletionTimeStamp:(double)arg1;
- (void)setGuidanceFeedbacks:(id)arg1;
- (void)setHasCompletedStep:(bool)arg1;
- (void)setHasCompletionTimeStamp:(bool)arg1;
- (void)setHasRouteIndex:(bool)arg1;
- (void)setHasStepID:(bool)arg1;
- (void)setInstructionErrors:(id)arg1;
- (void)setRouteID:(id)arg1;
- (void)setRouteIndex:(unsigned int)arg1;
- (void)setStepID:(unsigned int)arg1;
- (unsigned int)stepID;
- (void)writeTo:(id)arg1;

@end
