/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOSpatialLookupRequestConfig : GEOServiceRequestDefaultConfig {
    double  _timeout;
}

- (id)initWithTimeout:(double)arg1;
- (unsigned char)requestCounterInfoTypeForRequest:(id)arg1;
- (unsigned long long)urlType;

@end
