/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOSpokenGuidanceFeedback : PBCodable <NSCopying> {
    float  _duration;
    struct { 
        unsigned int duration : 1; 
        unsigned int spokenGuidanceIndex : 1; 
    }  _has;
    int  _spokenGuidanceIndex;
}

@property (nonatomic) float duration;
@property (nonatomic) bool hasDuration;
@property (nonatomic) bool hasSpokenGuidanceIndex;
@property (nonatomic) int spokenGuidanceIndex;

- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (float)duration;
- (bool)hasDuration;
- (bool)hasSpokenGuidanceIndex;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setDuration:(float)arg1;
- (void)setHasDuration:(bool)arg1;
- (void)setHasSpokenGuidanceIndex:(bool)arg1;
- (void)setSpokenGuidanceIndex:(int)arg1;
- (int)spokenGuidanceIndex;
- (void)writeTo:(id)arg1;

@end
