/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOSQLiteDB : NSObject {
    struct sqlite3 { } * _db;
    NSString * _dbFilePath;
    NSMutableArray * _filesAddedDuringTransaction;
    NSMutableArray * _filesDeletedDuringTransaction;
    bool  _isInTransaction;
    NSError * _lastError;
    char * _logFacility;
    NSMapTable * _preparedStatements;
    NSObject<OS_dispatch_queue> * _queue;
    id /* block */  _setupBlock;
    int  _sqliteFlags;
}

@property (nonatomic, readonly) NSString *dbFilePath;
@property (nonatomic, readonly) bool isDBReady;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *isolationQueue;
@property (nonatomic, readonly) NSError *lastError;
@property (nonatomic, readonly) struct sqlite3 { }*sqliteDB;

- (void).cxx_destruct;
- (bool)_bindParameter:(const char *)arg1 inStatement:(struct sqlite3_stmt { }*)arg2 error:(id*)arg3 withBinder:(id /* block */)arg4;
- (id)_blobForColumn:(int)arg1 inStatment:(struct sqlite3_stmt { }*)arg2 noCopy:(bool)arg3;
- (void)_debug_lockDB:(id)arg1;
- (void)_debug_unlockDB:(id)arg1;
- (void)_execute:(id /* block */)arg1 errorHandler:(id /* block */)arg2;
- (bool)bindBlobNoCopyParameter:(const char *)arg1 toValue:(id)arg2 inStatement:(struct sqlite3_stmt { }*)arg3 error:(id*)arg4;
- (bool)bindBlobParameter:(const char *)arg1 toValue:(id)arg2 inStatement:(struct sqlite3_stmt { }*)arg3 error:(id*)arg4;
- (bool)bindInt64Parameter:(const char *)arg1 toValue:(long long)arg2 inStatement:(struct sqlite3_stmt { }*)arg3 error:(id*)arg4;
- (bool)bindIntParameter:(const char *)arg1 toValue:(int)arg2 inStatement:(struct sqlite3_stmt { }*)arg3 error:(id*)arg4;
- (bool)bindRealParameter:(const char *)arg1 toValue:(double)arg2 inStatement:(struct sqlite3_stmt { }*)arg3 error:(id*)arg4;
- (bool)bindTextParameter:(const char *)arg1 toValue:(id)arg2 inStatement:(struct sqlite3_stmt { }*)arg3 error:(id*)arg4;
- (id)blobForColumn:(int)arg1 inStatment:(struct sqlite3_stmt { }*)arg2;
- (void)clearStatement:(id)arg1;
- (bool)createTable:(const char *)arg1 withDrop:(const char *)arg2;
- (id)dbFilePath;
- (void)dealloc;
- (bool)deleteExternalResourceAtURL:(id)arg1 error:(id*)arg2;
- (double)doubleForColumn:(int)arg1 inStatment:(struct sqlite3_stmt { }*)arg2;
- (void)executeAsync:(id /* block */)arg1;
- (void)executeAsync:(id /* block */)arg1 errorHandler:(id /* block */)arg2;
- (bool)executeInTransaction:(id /* block */)arg1;
- (bool)executeStatement:(struct sqlite3_stmt { }*)arg1 error:(id*)arg2;
- (bool)executeStatement:(id)arg1 statementBlock:(id /* block */)arg2;
- (void)executeSync:(id /* block */)arg1;
- (void)executeSync:(id /* block */)arg1 errorHandler:(id /* block */)arg2;
- (id)initWithQueueName:(const char *)arg1 logFacility:(const char *)arg2 dbFilePath:(id)arg3 sqliteFlags:(int)arg4 setupBlock:(id /* block */)arg5;
- (long long)int64ForColumn:(int)arg1 inStatment:(struct sqlite3_stmt { }*)arg2;
- (int)intForColumn:(int)arg1 inStatment:(struct sqlite3_stmt { }*)arg2;
- (bool)isDBReady;
- (id)isolationQueue;
- (id)lastError;
- (id)noCopyBlobForColumn:(int)arg1 inStatment:(struct sqlite3_stmt { }*)arg2;
- (bool)prepareStatement:(const char *)arg1 forKey:(id)arg2;
- (bool)reportSQLiteErrorCode:(int)arg1 method:(id)arg2 error:(id*)arg3;
- (bool)setup;
- (struct sqlite3 { }*)sqliteDB;
- (struct sqlite3_stmt { }*)statementForKey:(id)arg1;
- (bool)statementForKey:(id)arg1 statementBlock:(id /* block */)arg2;
- (id)stringForColumn:(int)arg1 inStatment:(struct sqlite3_stmt { }*)arg2;
- (void)tearDown;
- (bool)writeExternalResourceWithData:(id)arg1 toURL:(id)arg2 error:(id*)arg3;

@end
