/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOTrafficProbeLocalProxy : NSObject <GEOTrafficProbeProxy>

- (void)reportBatchTrafficProbes:(id)arg1;
- (void)reportRealtimeTrafficProbes:(id)arg1 probeCount:(unsigned long long)arg2 recvTime:(id)arg3 forTripId:(id)arg4;

@end
