/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOTestTileRequester : GEOTileRequester {
    NSTimer * _timer;
}

+ (unsigned char)tileProviderIdentifier;

- (void).cxx_destruct;
- (void)_sendResults:(id)arg1;
- (void)dealloc;
- (void)start;

@end
