/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOToolLocalProxy : NSObject <GEOToolProxy>

- (void)lockDBs;
- (void)resetMapDataExtension;
- (void)unlockDBs;

@end
