/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVFigRouteDescriptorOutputDeviceFactory : NSObject <AVOutputDeviceFactory>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)outputDeviceForCurrentRouteOfRoutingContext:(struct OpaqueFigRoutingContext { }*)arg1;
+ (id)outputDevicesForCurrentRoutesOfRoutingContext:(struct OpaqueFigRoutingContext { }*)arg1;

@end
