/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVFigGroupIDOutputDeviceGroupImpl : NSObject <AVOutputDeviceGroupImpl> {
    struct __CFString { } * _groupID;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) const struct __CFString { }*figGroupID;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void)dealloc;
- (const struct __CFString { }*)figGroupID;
- (id)initWithFigGroupID:(struct __CFString { }*)arg1;

@end
