/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVFigEndpointPickerOutputDeviceDiscoverySessionImpl : NSObject <AVOutputDeviceDiscoverySessionImpl> {
    struct OpaqueFigEndpointPicker { } * _endpointPicker;
    unsigned long long  _features;
    AVOutputDeviceDiscoverySession * _parentSession;
    NSObject<OS_dispatch_queue> * _pickerQueue;
    AVWeakReference * _weakReference;
}

@property (readonly) NSArray *availableOutputDeviceGroups;
@property (nonatomic, readonly) AVOutputDeviceDiscoverySessionAvailableOutputDevices *availableOutputDevicesObject;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) bool devicePresenceDetected;
@property (readonly) unsigned long long hash;
@property AVOutputDeviceDiscoverySession *parentOutputDeviceDiscoverySession;
@property (readonly) Class superclass;

+ (void)initialize;
+ (id)outputDeviceDiscoverySessionImplWithDeviceFeatures:(unsigned long long)arg1;

- (void).cxx_destruct;
- (void)_addFigEndpointPickerNotifications;
- (int)_configureFigEndpointPickerWithFeature:(unsigned long long)arg1;
- (void)_handlePickerServerConnectionDiedNotification;
- (void)_removeFigEndpointPickerNotifications;
- (id)availableOutputDeviceGroups;
- (id)availableOutputDevicesObject;
- (void)dealloc;
- (bool)devicePresenceDetected;
- (id)init;
- (id)initWithDeviceFeatures:(unsigned long long)arg1;
- (void)outputDeviceDiscoverySessionDidChangeDiscoveryMode:(id)arg1;
- (id)parentOutputDeviceDiscoverySession;
- (void)setParentOutputDeviceDiscoverySession:(id)arg1;

@end
