/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVFigRouteDiscovererOutputDeviceDiscoverySessionImpl : NSObject <AVOutputDeviceDiscoverySessionImpl> {
    struct OpaqueFigRouteDiscoverer { } * _discoverer;
    AVOutputDeviceDiscoverySession * _parentSession;
    id /* block */  _routeDiscovererCreator;
    AVWeakReference * _weakObserver;
}

@property (readonly) NSArray *availableOutputDeviceGroups;
@property (nonatomic, readonly) AVOutputDeviceDiscoverySessionAvailableOutputDevices *availableOutputDevicesObject;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) bool devicePresenceDetected;
@property (readonly) unsigned long long hash;
@property AVOutputDeviceDiscoverySession *parentOutputDeviceDiscoverySession;
@property (readonly) Class superclass;

+ (void)initialize;
+ (id)outputDeviceDiscoverySessionImplWithDeviceFeatures:(unsigned long long)arg1;

- (void).cxx_destruct;
- (void)_availableRoutesChanged;
- (void)_routePresentChanged;
- (void)_serverDied;
- (id)availableOutputDeviceGroups;
- (id)availableOutputDevicesObject;
- (void)dealloc;
- (bool)devicePresenceDetected;
- (id)init;
- (id)initWithFigRouteDiscovererCreator:(id /* block */)arg1;
- (void)outputDeviceDiscoverySessionDidChangeDiscoveryMode:(id)arg1;
- (id)parentOutputDeviceDiscoverySession;
- (void)setParentOutputDeviceDiscoverySession:(id)arg1;

@end
