/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVOutputContextCommunicationChannel : NSObject {
    AVOutputContextCommunicationChannelInternal * _ivars;
}

@property (nonatomic, readonly) <AVOutputContextCommunicationChannelImpl> *impl;

- (void)dealloc;
- (id)impl;
- (id)init;
- (id)initWithOutputContextCommunicationChannelImpl:(id)arg1;
- (void)sendData:(id)arg1 completionHandler:(id /* block */)arg2;

@end
