/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVOutputContextManagerInternal : NSObject {
    <AVOutputContextManagerImpl> * impl;
}

@end
