/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVOutputDeviceGroup : NSObject {
    AVOutputDeviceGroupInternal * _ivars;
}

@property (nonatomic, readonly) AVFigGroupIDOutputDeviceGroupImpl *figGroupIDOutputDeviceGroupImpl;

+ (id)outputDeviceGroupWithFigGroupID:(struct __CFString { }*)arg1;

- (void)dealloc;
- (id)figGroupIDOutputDeviceGroupImpl;
- (id)impl;
- (id)init;
- (id)initWithOutputDeviceGroupImpl:(id)arg1;

@end
